#!/bin/sh -efu

. shell-error

usage()
{
	[ -z "$*" ] || message "$*"
	echo >&2 "usage: $PROG <reponame> <taskno>"
	exit 1
}

[ $# -ge 2 ] || usage 'Not enough arguments.'
[ $# -le 2 ] || usage 'Too many arguments.'

repo="$1"; shift
task="$1"; shift

exec ssh repo reposit "$repo" "$task"
