#!/bin/sh -efu

need_deps_default='rpmlib\(PayloadIsLzma\).*'
need_deps_sisyphus='rpmlib\(PayloadIs(Lzma|Xz)\).*'

# check for unacceptable policy requirements
check_policyreq()
{
	local f="$1" && shift || return 1
	local rc=0
	local var need_deps bad

	var="need_deps_${GB_REPO_NAME//./_}"
	eval "need_deps=\"\${$var:-\$need_deps_default}\""
	if ! printf %s "$rpm_requires" |cut -d' ' -f1 |egrep -qsx "$need_deps"; then
		FileError "missing mandatory requires: $(oneliner "$need_deps")" "$f"
		rc=1
	fi

	return $rc
}

run_check() {
	if ! check_policyreq "$1"; then
		CheckError 'package dependencies violation'
		return 1
	fi
}
