#!/bin/sh -efu

: ${package_type?} ${rpm_requires?}

# check for unacceptable policy requirements
check_policyreq()
{
	local f="$1" && shift || return 1
	local rc=0
	local need_reqs var
	if [ "${GB_SKIP_POLICYDEPS_CHECK_FOR_SRC_PACKAGES-}" = yes ] &&
	   [ "$package_type" = src ]; then
		return 0
	fi
	var="GB_REPO_MANDATORY_${package_type}_REQS"
	var="${var^^}"
	eval "need_reqs=\"\${$var:-\${GB_REPO_MANDATORY_PKG_REQS-}}\""

	if [ -n "$need_reqs" ] &&
	   ! printf %s "$rpm_requires" |cut -d' ' -f1 |grep -E -qsx "$need_reqs"; then
		FileError "missing mandatory requires: $(oneliner "$need_reqs")" "$f"
		rc=1
	fi

	return $rc
}

run_check() {
	if ! check_policyreq "$1"; then
		CheckError 'package dependencies violation'
		return 1
	fi
}
