#!/bin/sh -efu

. shell-error

GA_REPO_NAME=site
export GA_REPO_NAME

# Prepend the path to scripts.
[ "${0%/*}" != "$0" ] ||
	fatal 'Where am I?'
PATH="${0%/*}:$PATH"

. ga-sh-functions

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NEW-REPO-NAME> <FROM-REPO-NAME>"
	exit 1
}

[ $# -ge 2 ] ||
	usage 'Not enough arguments.'
[ $# -le 2 ] ||
	usage 'Too many arguments.'

new_repo="$1"; shift
from_repo="$1"; shift

printf %s "$new_repo" | grep -xqs '[a-z][a-z_0-9.]\+' ||
	fatal "$new_repo: invalid NEW-REPO-NAME specified"
printf %s "$from_repo" | grep -xqs '[a-z][a-z_0-9.]\+' ||
	fatal "$from_repo: invalid FROM-REPO-NAME specified"

conf_dir="/usr/libexec/girar-archiver"
cd "$conf_dir"
[ ! -f "ga-sh-conf-$new_repo" ] ||
	fatal "$new_repo: config file already exists"
[ -f "ga-sh-conf-$from_repo" ] ||
	fatal "$from_repo: config file not found"

cd "$GA_REPO_ROOT"

from_latest="$(readlink -ev -- "$from_repo/latest")"
install -d -o root -g ga_repo -m1775 -- "$new_repo" "$new_repo/task"
install -d -o root -g ga_upload -m1775 -- "$new_repo/date"
install -d -o root -g ga_tasker -m1775 -- "$new_repo/.tmp"
ln -snr -- "$from_latest" "$new_repo/branched"
chown -h -- ga_repo:ga_repo "$new_repo/branched"
cp -a -- "$new_repo/branched" "$new_repo/latest"

cd "$conf_dir"
sed "s/$from_repo/$new_repo/g" < "ga-sh-conf-$from_repo" > "ga-sh-conf-$new_repo"

message "Consider creation of $GA_UPLOAD_DIR/copy/$new_repo directory"
