#!/bin/sh -efu

GA_REPO_NAME=site
. ga-sh-functions
. shell-temp

cd "$GA_REPO_ROOT"

create_temporary tmpdir

set +f

{
	head -qn1 -- [a-z0-9]*/task/task.list
	tail -qn1 -- [a-z0-9]*/task/task.list
} > "$tmpdir/exclude.list"

for repo in [a-z0-9]*; do
	[ -f /usr/libexec/girar-archiver/ga-sh-conf-$repo ] || continue
	[ -s "$repo"/task/task.list ] || continue
	GA_REPO_NAME="$repo" "$0-repo" "$tmpdir/exclude.list"
done
