#!/bin/sh -efu

exec < /dev/null

. ga-sh-functions

[ -n "${GA_SQUEEZE_MTIME-}" ] &&
[ "$GA_SQUEEZE_MTIME" -gt 0 ] || exit 0

task="$1"; shift
dir="_$(($task/1024))"

cd "$GA_REPO_DIR/task/$dir/$task"

[ -d noarch ] || exit 0
[ -w files/list ] || exit 0
[ -s files/list/task.info -a -s files/list/src.hash.xz ] || exit 0
[ -n "$(find files/list/task.info -maxdepth 0 -type f -mtime +"$GA_SQUEEZE_MTIME")" ] ||
	exit 0

utask="$(sed -n "/^$task\$/,\$ p" "$GA_REPO_DIR/task/task.list" |
	diff -U1 - "$GA_UPLOAD_DIR/log/$GA_REPO_NAME.log" |
	sed '/^ /!d;s///;q')"
[ -n "$utask" ] &&
	[ "$task" != "$utask" ] ||
	exit 0
udir="_$(($utask/1024))"

enable -f /usr/lib/bash/lockf lockf
builtin lockf -n . || exit 0

logger -t "${0##*/}" "squeezing: $PWD"
echo "$task" >> "$GA_REPO_DIR/task/squeeze.list"

chmod u+w .
find -mindepth 1 -not -type d -not -path './files/list/*' -delete
find -mindepth 1 -depth -type d -exec rmdir --ignore-fail-on-non-empty -- '{}' ';'
[ -L daily ] || ln -rs "../../$udir/$utask" daily
touch -r files/list/task.info .
chmod a-w .
