#!/bin/sh -efu

exec < /dev/null

. ga-sh-conf

k="$1"; shift

n="$(($k/1024))"
k="$(($k%1024))"
dir_emptydir="$GA_SYMLINK_DIR/emptydir/$n"
dir_nullfile="$GA_SYMLINK_DIR/nullfile/$n"
mkdir -p -- "$dir_emptydir" "$dir_nullfile"
emptydir="$dir_emptydir/$k"
nullfile="$dir_nullfile/$k"

for dir; do
	[ -d "$dir" -a -f "$dir/config" -a -L "$dir/objects" ] ||
		continue
	dest="$dir/refs"
	[ -e "$dest" ] || {
		flock 0
		[ -L "$emptydir" ] ||
			ln -sn -- /var/empty "$emptydir"
		ln -n -- "$emptydir" "$dest"
	} < "$dir_emptydir"
	dest="$dir/git-daemon-export-ok"
	[ -e "$dest" ] || {
		flock 0
		[ -L "$nullfile" ] ||
			ln -sn -- /dev/null "$nullfile"
		ln -n -- "$nullfile" "$dest"
	} < "$dir_nullfile"
	touch -hr "$dir/objects" "$dir"
done
