#!/bin/sh -efu

[ $# = 2 ]
src="$1"; shift
dst="$1"; shift
[ -d "$src" ]
[ ! -e "$dst" ]

cp -al -- "$src" "$dst"
cd "$dst"

find -type f \
     -not -user ga_depot \
     -not -user ga_repo \
     -not -uid 0 -print0 |
	xargs -r0 ga-x-repo-copyself
