#!/bin/sh -efu

. gb-sh-functions

id="$1"; shift

cd "$GB_TASKS_DIR/$id"
enable -f /usr/lib/bash/lockf lockf
# obtain an exclusive lock on the TASKS structure
builtin lockf -v .

if [ "$(cat task/state)" != BUILDING ]; then
	echo >&2 "Task $id is not selected for build"
	exit 1
fi

try=$(cat task/try)
iter=$(cat task/iter)
log="task/log.$try.$iter"
gb-task-set-summary

(umask 002 && > task/acl-addressees && > task/unmet-addressees) || exit

(
	exec >>"$log" 2>&1
	shared_task="$(find gears -maxdepth 0 -path gears -type d -perm -g=w -printf 'shared ' 2>/dev/null ||:)"
	[ "$try" = 1 ] && text=started || text=resumed
	started_by="$(stat -c %U "${log%.*}.1")"
	started_by="${started_by#git_}"
	stamp_echo "${shared_task}task #$id for $GB_REPO_NAME $text by $started_by:"
	gb-task-show
	PATH="$PATH:/usr/libexec/girar" girar-make-task-index-html "$id" ||:

	# Prepare changes
	gb-task-pkgtar
	gb-clone-repo-dir; export GB_REPO_DIR="$GB_CLONED_REPO_DIR"
	gb-task-gen-buildrepo
	gb-task-setup-remote
	gb-task-copy-packages
	gb-task-build
	PATH="$PATH:/usr/libexec/girar" girar-make-task-index-html "$id" ||:

	# Run basic tests
	gb-task-check-build
	gb-task-check-noarch
	gb-task-repo-plan
	gb-task-repo-vercheck
	gb-task-gen-testrepo
	gb-task-repo-unmets
	gb-task-repo-elfsym
	gb-task-check-install

	gb-task-gen-taskrepo "$id"
	gb-task-save-repo

	# Run surmountable tests
	gb-task-local-policy
	gb-task-check-girar
	gb-task-check-lastchange
	gb-task-check-acl

	gb-task-find-closed-bugs
)

rc=$?
[ "$rc" = 0 ] &&
	state=TESTED ||
	state=FAILED

stamp_echo >>"$log" "task #$id for $GB_REPO_NAME $state"
echo "$state" > task/state

if [ "$rc" != 0 -o -f task/test-only ]; then
	gb-task-send-email "$id"
else
	echo PENDING > task/state
	gb-task-validate-pending ||:
fi

PATH="$PATH:/usr/libexec/girar" girar-make-task-index-html "$id" ||:

exit $rc
