#!/bin/sh -efu

. gb-sh-functions

enable -f /usr/lib/bash/lockf lockf
# Obtain a shared lock on the $GB_REPO_DIR.
if ! builtin lockf -sn "$GB_REPO_DIR"; then
	stamp_echo "waiting for a shared lock on $GB_REPO_NAME repository"
	builtin lockf -sv "$GB_REPO_DIR"
	stamp_echo "acquired a shared lock on $GB_REPO_NAME repository"
fi

repo="${GB_REPO_DIR##*/}"

. gb-sh-tmpdir

for host in $GB_REPO_MIRRORS; do
	ssh "$host" "$repo" ||
		stamp_echo "FAILED to clone $repo on $host" >> "$tmpdir"/FAIL &
done

(
	mkdir -p -- "$GB_CLONED_REPO_DIR"
	[ ! -d "$GB_CLONED_REPO_DIR" ] ||
		chmod u+w -- "$GB_CLONED_REPO_DIR"
	rm -rf -- "$GB_CLONED_REPO_DIR"
	cp -al "$GB_REPO_DIR" "$GB_CLONED_REPO_DIR"
) || stamp_echo "FAILED to clone $repo" >> "$tmpdir"/FAIL

wait

if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	halt_build_queue
fi

stamp_echo >&2 "cloned $repo"
