#!/bin/sh -efu

. gb-sh-functions

guard=16528
[ -d "$GB_TASKS_DIR/$guard/build" ] &&
[ "$(cat $GB_TASKS_DIR/$guard/task/rc)" != 0 ] &&
[ "$(cat task/id)" != "$guard" ] ||
exit 0

. gb-sh-tmpdir

find $GB_TASKS_DIR/$guard/build/ -mindepth 3 -maxdepth 3 -name chroot_\* -type f -print0 |
	xargs -r0 cut -f1 -- $GB_TASKS_DIR/$guard/plan/add-bin $GB_TASKS_DIR/$guard/plan/rm-bin |
	sort -u >"$tmpdir"/guard
cut -f1 plan/add-bin plan/rm-bin |
	sort -u >"$tmpdir"/change
comm -12 "$tmpdir"/guard "$tmpdir"/change >"$tmpdir"/affected
if [ -s "$tmpdir"/affected ]; then
	stamp_echo >&2 "following just built binary packages affect task #$guard:"
	echo "$(oneliner "$(cat "$tmpdir"/affected)")"
	stamp_echo >&2 "please try again later"
	exit 1
fi
