#!/bin/sh -efu

. gb-sh-functions

RC=0

while read -r N EVR A F; do
	bin=$(findbin "$F")
	if py25_deps=$(rpmquery --requires --provides -p "$bin" |
		grep 'python2\.5\|python = 2\.5\|libpython2\.5' )
	then
		echo >&2 $F: $py25_deps
		RC=1
	fi
done <plan/add-bin

if [ $RC -gt 0 ]; then
	stamp_echo >&2 'python2.5 dependencies forbidden'
	stamp_echo >&2 'sorry for inconvenience, please try again later'
	exit 1
fi
