#!/bin/sh -e

. gb-sh-functions

template="$GB_HOME/template"

mkidx()
{
	local type="$1"; shift
	local opts="$1"; shift

	sed "s|@DIR@|$PWD|g" <"$template/git-header-$type.html.in" >"$tmpdir/file"

	ls $opts |while read -r f; do
		name="${f%.git}"
		[ "$name" != "$f" ] || continue
		date="$(LANG=C date +%d-%b-%Y -r "$f")"
		sed -e "s|@DIR@|$PWD|g" -e "s|@NAME@|$name|g" -e "s|@DATE@|$date|g" \
			<"$template/git-entry.html.in"
	done >>"$tmpdir/file"

	cat <"$template/git-footer.html" >>"$tmpdir/file"

	cmp -s "index-$type.html" "$tmpdir/file" ||
		mv "$tmpdir/file" "index-$type.html"
}

. gb-sh-tmpdir

for d; do
	[ -d "$d" ] || continue
	cd "$d"
	mkidx name ''
	mkidx date -t
	[ -L index.html ] ||
		ln -snf index-name.html index.html
	cd - >/dev/null
done

stamp_echo >&2 'gears dir index update OK'

