#!/bin/sh -efu

. gb-sh-conf-$USER
: ${GB_REPO_NAME:?}
. gb-sh-conf-$GB_REPO_NAME

: ${GB_REPO_NAME:?} ${GB_REPO_LABEL:?} ${GB_REPO_DIR:?} ${GB_REPO_SIGNER:?} ${GB_REPO_CODENAME:?} ${GB_REPO_EMAIL:?} ${GB_REPO_MIRRORS:?}
: ${GB_REPO_RPMARGS?}
: ${GB_REPO_UP_NAME?} ${GB_REPO_DOWN_NAME?}
: ${GB_REPO_REL_SUFF_MUST_NOT?} ${GB_REPO_REL_SUFF_MUST_HAVE?}
: ${GB_GEARS_DIR:?}
: ${GB_SRPMS_DIR:?}
: ${GB_TASKS_DIR:?} ${GB_TASKS_DONE_DIR:?}
: ${GB_META_DIR:?}

: ${GB_BUGZILLA_FROM:?}
: ${GB_BUGZILLA_TO:?}
: ${GB_BUGZILLA_KEY:?}

: ${GB_EMAIL_DOMAIN:?}

[ -z "${arch-}" ] ||
	remote_host="build-$GB_REPO_NAME-$arch"
