#!/bin/sh -efu

. gb-sh-functions

cd "$GB_TASKS_DIR"

enable -f /usr/lib/bash/lockf lockf
# obtain a shared lock on the whole TASKS directory
builtin lockf -s .

repo_tasks()
{
	find . -mindepth 3 -maxdepth 3 -path './[1-9]*/task/repo' -type f -print0 |
		xargs -r0 fgrep -i -l -x -e "$GB_REPO_NAME" -- |
		cut -d/ -f2 |sort -n
}


select_task()
{
	local id="$1"; shift
	cd "$id" 2>/dev/null
	# obtain an exclusive lock on the TASKS structure
	# if the lock cannot be immediately acquired, fail
	builtin lockf -n .

	# if task sequence number is not set, fail
	[ -s task/seq ]

	local seq
	seq=$(cat task/seq)
	# if the task is not ready to run, fail
	[ -n "$seq" ]
	[ "$(($seq%3))" -eq 0 ]

	seq=$(($seq+1))
	echo "$seq" >task/seq ||
		halt_build_queue
}

for id in $(repo_tasks); do
	(select_task "$id")
	if [ $? -eq 0 ]; then
		echo "$id"
		exit
	fi
done
