#!/bin/sh -efu

. gb-sh-repo-conf

cd "$GIRAR_TASKS"

repo_tasks()
{
	set +f
	fgrep -l -i -x "$GB_REPO_NAME" [1-9]*/task/repo |
	sort -n |cut -d/ -f1
}

enable -f /usr/lib/bash/lockf lockf

select_task()
{
	local id="$1"; shift
	cd "$id"
	builtin lockf -n .
	[ -s task/seq ]
	local seq
	seq=$(cat task/seq)
	[ -n "$seq" ]
	[ "$(($seq%3))" -eq 0 ]
	seq=$(($seq+1))
	echo "$seq" >task/seq
}

for id in $(repo_tasks); do
	(select_task "$id")
	if [ $? -eq 0 ]; then
		echo "$id"
		exit
	fi
done
