#!/bin/sh -efu

. gb-sh-repo-conf

gb_hasher_num()
{
	local arch="$1"; shift
	case "$arch" in
		i586)
			echo 1 ;;
		x86_64)
			echo 2 ;;
		*)
			echo >&2 "unsupported architecture: $arch"
			return 1 ;;
	esac
}

gb_hasher_dir()
{
	local arch="$1"; shift
	dir="$TMPDIR/gb-hasher/$arch"
	mkdir -p "$dir"
	echo "$dir"
}

gb_hasher_aptconf()
{
	local arch="$1"; shift
	mkdir -p "$TMPDIR/gb-hasher"
	cat >"$TMPDIR/gb-hasher/$arch-sources.list" <<EOF
rpm file:$GB_REPO_DIR $arch classic
rpm file:$GB_REPO_DIR noarch classic
EOF
	cat >"$TMPDIR/gb-hasher/$arch-apt.conf" <<EOF
Dir::Etc::main "/dev/null";
Dir::Etc::parts "/var/empty";
Dir::Etc::sourcelist "$TMPDIR/gb-hasher/$arch-sources.list";
Dir::Etc::sourceparts "/var/empty";
EOF
	echo "$TMPDIR/gb-hasher/$arch-apt.conf"
}
