#!/bin/sh -efu

. gb-sh-functions

id="$1"; shift
cd "$GB_TASKS_DIR/$id"

[ "$(cat task/rc)" = 0 -a ! -f task/test-only ] ||
	exit 0

find plan -type f -name 'next.*' -delete

cd "$GB_TASKS_DIR"
k="_$(($id/1024))"
mkdir -p "$GB_TASKS_DONE_DIR/$k"
mv -- "$id" "$GB_TASKS_DONE_DIR/$k/"
