#!/bin/sh -efu

. gb-sh-functions
. gb-sh-tmpdir

# update src.hash
cut -f3 < plan/rm-src > $tmpdir/rm-src-F
sort -o $tmpdir/rm-src-F{,}
join -1 1 -2 2 -v2 -o 2.1,2.2 $tmpdir/rm-src-F $GB_REPO_DIR/files/list/src.hash \
	> $tmpdir/src.hash
sed -i 's/ /  /' $tmpdir/src.hash

while read -r N EVR F P I; do
	hash="$(sha256sum "$P")"
	hash="${hash%% *}"
	printf '%s  %s\n' "$hash" "$F"
done < plan/add-src >> $tmpdir/src.hash
sort -k2,2 -o $tmpdir/src.hash{,}
install -pm644 -- $tmpdir/src.hash $GB_REPO_DIR/files/list/src.hash

# update $arch.hash files
cut -f4 < plan/rm-bin > $tmpdir/rm-bin-F
sort -o $tmpdir/rm-bin-F{,}
while read -r arch; do
	join -1 1 -2 2 -v2 -o 2.1,2.2 $tmpdir/rm-bin-F $GB_REPO_DIR/files/list/$arch.hash \
		> $tmpdir/$arch.hash
	sed -i 's/ /  /' $tmpdir/$arch.hash

	while read -r N EVR A F P I; do
		[ "$A" = "$arch" ] || continue
		hash="$(sha256sum "$P")"
		hash="${hash%% *}"
		printf '%s  %s\n' "$hash" "$F"
	done < plan/add-bin >> $tmpdir/$arch.hash
	sort -k2,2 -o $tmpdir/$arch.hash{,}
	install -pm644 -- $tmpdir/$arch.hash $GB_REPO_DIR/files/list/$arch.hash
done < plan/change-arch

# update arepo $arch.hash files
for arch in ${GB_AREPO_ARCH-}; do
	[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] ||
		continue
	join -1 1 -2 2 -v2 -o 2.1,2.2 plan/arepo-rm-$arch $GB_REPO_DIR/files/list/$arch.hash \
		> $tmpdir/$arch.hash
	sed -i 's/ /  /' $tmpdir/$arch.hash

	while read -r N EVR F dummy; do
		P="arepo/$arch/rpms/$F"
		hash="$(sha256sum "$P")"
		hash="${hash%% *}"
		printf '%s  %s\n' "$hash" "$F"
	done < plan/arepo-add-$arch >> $tmpdir/$arch.hash
	sort -k2,2 -o $tmpdir/$arch.hash{,}
	install -pm644 -- $tmpdir/$arch.hash $GB_REPO_DIR/files/list/$arch.hash
done
