#!/bin/sh -efu

gear_nums()
{
	set +f
	cd gears &&
	ls -1 [1-9]*/dir |sort -n |cut -d/ -f1
}

nums=$(gear_nums)

for i in $nums; do
	if [ -s gears/$i/pkg.tar ]; then
		continue
	fi
	dir=$(cat gears/$i/dir)
	tag_name=$(cat gears/$i/tag_name)
	if GIT_DIR=gears/$i/git gear -t "$tag_name" -- gears/$i/pkg.tar &&
	   [ -s gears/$i/pkg.tar ]; then
		echo >&2 "created pkg.tar for ${dir##*/} $tag_name"
	else
		echo >&2 "cannot create pkg.tar for ${dir##*/} $tag_name"
		exit 1
	fi
done
