#!/bin/sh -efu

. gb-sh-functions

# Use a fixed path so that genpkglist md5cache works.
repo="$TMPDIR/gb-repo-$GB_REPO_NAME"
rm -rf "$repo"
mkdir "$repo"

# symlinked repository clone
cp -prs -- $GB_REPO_DIR/{i586,x86_64,noarch} $repo/

. gb-sh-tmpdir

# dump old unmets
for arch in i586 x86_64; do
	cat >$tmpdir/$arch-sources.list <<EOF
rpm file:$repo $arch classic
rpm file:$repo noarch classic
EOF
	$arch unmets -s $tmpdir/$arch-sources.list >$tmpdir/$arch-unmets.old
done

# remove old binary files
while read -r N EVR A F; do
	rm -- $repo/$A/RPMS.classic/$F
done <plan/rm-bin

# add symlinks to new binary files
while read -r N EVR A F; do
	bin=$(findbin "$F")
	ln -s -- $PWD/$bin $repo/$A/RPMS.classic/$F
done <plan/add-bin

# regenerate apt indices
rm -r -- $repo/{i586,x86_64,noarch}/SRPMS.classic
rm -r -- $repo/{i586,x86_64,noarch}/base
for arch in i586 x86_64 noarch; do
	mkdir -- $repo/$arch/base
	genbasedir --topdir=$repo --no-oldhashfile --bz2only --mapi $arch classic
done

# dump new unmets
for arch in i586 x86_64; do
	$arch unmets -s $tmpdir/$arch-sources.list >$tmpdir/$arch-unmets.new
done

rc=0

cd "$tmpdir"
# compare unmets
for arch in i586 x86_64; do
	comm -13 $arch-unmets.{old,new} >$arch-unmets.plus
	comm -23 $arch-unmets.{old,new} >$arch-unmets.minus
	if [ -s $arch-unmets.plus ]; then
		echo "	$arch: NEW unmet dependencies detected:"
		awk -F'\t' '{printf "%-24s\t%s\n", $1, $2}' <$arch-unmets.plus
		rc=1
	fi >&2
	if [ -s $arch-unmets.minus ]; then
		echo "	$arch: old unmet dependencies resolved:"
		awk -F'\t' '{printf "%-24s\t%s\n", $1, $2}' <$arch-unmets.minus
	fi >&2
done

[ "$rc" = 0 ] && text=OK || text=FAILED
stamp_echo >&2 "dependencies check $text"
exit $rc
