#!/bin/sh -efu

. gb-sh-setup
. gb-sh-hasher-functions

id="$1" arch="$2"; shift 2
cd "$GB_TASKS/$id"

hsh_dir=$(gb_hasher_dir "$arch")
mkdir -p "$hsh_dir"
rm -rf "$hsh_dir"/repo

gear_nums()
{
	set +f
	cd gears &&
	ls -1 [1-9]*/dir |sort -n |cut -d/ -f1
}

nums=$(gear_nums)

for i in $nums; do
	$0-i "$id" "$arch" "$i"
done
