#!/bin/sh -efu

. gb-sh-functions

# Use a fixed path so that genpkglist md5cache works.
repo="$TMPDIR/gb-repo-$GB_REPO_NAME"
rm -rf "$repo"
mkdir "$repo"

# symlinked repository clone
cp -prs -- $GB_REPO_DIR/{files,i586,x86_64,noarch} $repo/

# apply changes
gb-y-task-commit-packages "$repo" >/dev/null
gb-y-repo-regen-basedir "$repo"

# basedir ok, SRPMS no longer needed
rm -r $repo/{i586,x86_64,noarch}/SRPMS.classic/
rm -r $repo/{i586,x86_64}/SRPMS.all/
rm -r $repo/files/SRPMS/

# not for build, contents_index not needed
rm $repo/{i586,x86_64,noarch}/base/contents_index

stamp_echo >&2 'created temporary repo'
