#!/bin/sh -efu

arch="$1"; shift
id="$1"; shift

. gb-sh-functions

topdir=build/repo
rm -rf $topdir/$arch
[ -s plan/arepo-add-$arch ] || exit 0
umask 002
mkdir -p $topdir/$arch/base
mkdir -p $topdir/$arch/RPMS.task

while read -r dummy dummy F dummy; do
	ln -s ../../../../arepo/$arch/rpms/$F $topdir/$arch/RPMS.task/
done < plan/arepo-add-$arch

GB_AREPO_COMPONENT_NAME=task GB_REPO_ARCHIVE="task $id" GB_REPO_DESCRIPTION="task $id" GB_REPO_LABEL="task $id" GB_REPO_SUITE="task $id" GB_REPO_VERSION="task $id" gb-y-arepo-genbasedir-arch $arch $topdir --bloat

#stamp_echo >&2 "[$arch] gen task repo OK"
