#!/bin/sh -efu

. gb-sh-functions

. gb-sh-tmpdir

for arch in i586 x86_64; do
	$0-arch "$arch" ||
		stamp_echo "[$arch] build FAILED" >>"$tmpdir"/FAIL &
done

wait

# Fail if at least one arch failed to build.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

stamp_echo >&2 'build OK'
