#!/bin/sh -efu

. gb-sh-functions

gb-y-task-commit-packages "$GB_REPO_DIR" >plan/commit.log
stamp_echo >&2 'packages update OK'

# update lists
install -pm644 -- plan/next.src "$GB_REPO_DIR/files/list/src.list"
install -pm644 -- plan/next.bin "$GB_REPO_DIR/files/list/bin.list"

gb-y-repo-regen-basedir "$GB_REPO_DIR"
stamp_echo >&2 'repo update OK'

gb-y-repo-regen-ci "$GB_REPO_DIR"
stamp_echo >&2 'contents_index update OK'
