#!/bin/sh -efu

. gb-sh-functions

enable -f /usr/lib/bash/lockf lockf
# obtain an exclusive lock on the $GB_META_DIR
builtin lockf -v "$GB_META_DIR"

while read -r N EVR F; do
	rm -rf $GB_META_DIR/$N/
done <plan/rm-src

while read -r N EVR F; do
	src=$N
	mkdir -p $GB_META_DIR/$src/srpm
	echo "$EVR" >$GB_META_DIR/$src/srpm/EVR
	srpm=$(findsrc "$F")
	gb-x-rpm-changelog $srpm >$GB_META_DIR/$src/srpm/changelog
	i=$(srpm2i "$F")
	for arch in i586 x86_64; do
		mkdir -p $GB_META_DIR/$src/srpm/$arch
		cat build/$i/$arch/log >$GB_META_DIR/$src/srpm/$arch/buildlog
		gb-x-fixup-buildlog $GB_META_DIR/$src/srpm/$arch/buildlog
		srpm=build/$i/$arch/srpm/$F
		rpmquery -R -p $srpm >$GB_META_DIR/$src/srpm/$arch/BR
		sed -i '/^rpmlib(/d' $GB_META_DIR/$src/srpm/$arch/BR
		sed -i 's/ *$//' $GB_META_DIR/$src/srpm/$arch/BR
		sort -u -o $GB_META_DIR/$src/srpm/$arch/BR{,}
	done
done <plan/add-src

while read -r src _ _ N EVR A F; do
	mkdir -p $GB_META_DIR/$src/rpms/$A/$N
	bin=$(findbin "$F")
	rpmquery --qf '%|EPOCH?{%{EPOCH}:}|%{VERSION}-%{RELEASE}\n' -p $bin >$GB_META_DIR/$src/rpms/$A/$N/EVR
	rpmquery --list -p $bin >$GB_META_DIR/$src/rpms/$A/$N/F
	for q in requires provides obsoletes conflicts; do
		Q=$(echo $q |sed 's/\(.\).*/\U\1/')
		rpmquery --$q -p $bin >$GB_META_DIR/$src/rpms/$A/$N/$Q
		sed -i 's/ *$//' $GB_META_DIR/$src/rpms/$A/$N/$Q
		sort -u -o $GB_META_DIR/$src/rpms/$A/$N/$Q{,}
	done
done <plan/add-src+bin
