#!/bin/sh -efu

. gb-sh-functions

id="$1"; shift
cd "$GB_TASKS_DIR/$id"

seq="$(cat task/seq)"
repo="$(cat task/repo)"
rc="$(cat task/rc)"
if [ "$rc" = 0 ]; then
	[ -f task/manual ] &&
		text=TESTED ||
		text=COMPLETE
else
	text=FAILED
fi
owner="$(cat task/owner)"

summary="$(cat task/summary)"
[ -n "$summary" ] || summary=' empty'
stripped_summary="$(printf %s "$summary" |fmt |head -n1)"
[ "$stripped_summary" = "$summary" ] ||
	stripped_summary="$stripped_summary ..."

try="$((1+$seq/3))"

. gb-sh-tmpdir

cat >"$tmpdir/draft" <<__EOF
To: git_$owner
Cc: $GB_REPO_EMAIL
Mail-Followup-To: $USER
X-girar-task-id: $id
X-girar-task-owner: $owner
X-girar-task-repo: $repo
X-girar-task-try: $try
X-girar-task-status: $text
X-girar-task-URL: $GB_SITE$GB_TASKS_DIR/$id/
__EOF

[ "$repo" != sisyphus ] ||
	repo=

[ $try -gt 1 ] || try=

[ "$stripped_summary" = "$summary" ] ||
	echo "X-girar-task-summary: [#$id]${repo:+ $repo} $text${try:+ (try $try)}$summary" >>"$tmpdir/draft"

echo "Subject: [#$id]${repo:+ $repo} $text${try:+ (try $try)}$stripped_summary" >>"$tmpdir/draft"

mutt -x -H "$tmpdir/draft" -a task/log </dev/null
