#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions

. shell-quote

# Prepare remote node for $arch install check.
# Note that now we use $remote_host:gb-repo, not $GB_REPO_DIR.
rsync -a "$GB_HOME/remote/" "$remote_host:"
remote_home=$(ssh "$remote_host" pwd)
ssh "$remote_host" ./gb-remote-plant \
	"\"$(quote_shell "$(cat task/owner)")\"" \
	"\"$(quote_shell "$GB_REPO_NAME")\"" \
	"\"$(quote_shell "$remote_home/gb-repo")\"" \
	"\"$(quote_shell "$arch")\"" \
	cache_dir=cache.check-install

# Generated with gb-task-gen-testrepo.
repo="$TMPDIR/gb-repo-$GB_REPO_NAME"

# Copy.
rsync -a --exclude '*list.classic.bz2' "$repo"/{$arch,noarch} "$remote_host:gb-repo/"

rc=0

while read -r N EVR A F; do
	[ "$A" = "$arch" -o "$A" = 'noarch' ] || continue
	if ssh "$remote_host" ./gb-remote-check-install \
	       "$GB_REPO_NAME" "$arch" "$N" "$EVR" "$A" "$F" </dev/null; then
		stamp_echo >&2 "[$arch] $N: install check OK"
	else
		stamp_echo >&2 "[$arch] $N: install check FAILED"
		rc=1
	fi
done <plan/add-bin

# Purge temporary repo.
rsync -a --delete /var/empty/ "$remote_host:gb-repo/"

exit $rc
