#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions
. gb-sh-tmpdir

for i in $(build_nums); do
	[ ! -s "build/$i/$arch/excluded" ] || continue
	find "build/$i/$arch/rpms" -mindepth 1 -maxdepth 1 -type f -execdir \
		rpmquery --qf '%{name}\n' -p -- '{}' '+'
done >"$tmpdir"/names

cd "$tmpdir"
sort -o names{,}
uniq -d names >dups

if [ -s dups ]; then
	stamp_echo >&2 "[$arch] duplicate packages: $(cat dups)"
	exit 1
fi
