#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

# Use a fixed path so that genpkglist md5cache works.
rm -rf "$GB_AREPO_DIR"
mkdir "$GB_AREPO_DIR"

. gb-sh-tmpdir

for arch in $GB_AREPO_ARCH; do
	$0-arch "$arch" ||
		stamp_echo "[$arch] gen next repo FAILED" >>"$tmpdir"/FAIL &
done

wait

# Fail if at least one arch failed to build.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

#stamp_echo >&2 'arepo gen next repo OK'
