#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions
. gb-sh-tmpdir

cd build
set +f
rpmquery --qf '%{name}\n' -p [1-9]*/$arch/rpms/*.rpm >"$tmpdir"/names
set -f

cd "$tmpdir"
sort -o names{,}
uniq -d names >dups

if [ -s dups ]; then
	stamp_echo >&2 "[$arch] duplicate packages: $(cat dups)"
	exit 1
fi
