#!/bin/sh -efu

. gb-sh-girar-conf

srpm2i()
{
	local f="$1"; shift
	cd build
	set +f
	set -- [1-9]*/*/srpm/"$f"
	if ! [ -f "$1" ]; then
		echo " *** cannot find $f under build/"
		return 1
	fi >&2
	local IFS=/
	set -- $1
	echo "$1"
}

girar_commit()
{
	local N="$1" i="$2"; shift 2
	local old
	local tag
	tag=$(cat gears/$i/tag_name)
	if old=$(cd "$GB_REAL_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# real gear
		(cd gears/$i/git &&
		 git push --tags "$GB_REAL_GEARS"/"$N".git "$tag":"$GB_GEAR_BRANCH") || false
	elif old=$(cd "$GB_SRPM_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# srpm gear
		(cd gears/$i/git &&
		 git push --tags "$GB_SRPM_GEARS"/"$N".git "$tag":"$GB_GEAR_BRANCH") || false
	else
		# fist-time push
		echo >&2 "$N.git: first-time push, don't know what to do"
		return 1
	fi
}

while read -r N EVR F; do
	i=$(srpm2i "$F")
	girar_commit "$N" "$i"
done <plan/add-src

