#!/bin/sh
set -efu

. gb-sh-functions

mkdir -p bugmail

while read N EVR F; do
	srpm=$(findsrc "$F")
	s='[:space:]'
	changelog=$(rpmquery -p --lastchange "$srpm" |
		sed -r "s/(<[$s]*[^@>$s]+([$s]*@[$s]*|[$s]+at[$s]+)(packages[$s]*[.][$s]*)?altlinux)([$s]*[.][$s]*|[$s]+dot[$s]+)[[:alpha:]]+[$s]*>/\\1>/")
	ids=$(printf '%s\n' "$changelog" |gb-x-parse-bugs-from-changelog)
	[ -n "$ids" ] || continue
	stamp_echo >&2 "$N: closing bugs: $ids"
	binaries=$(printf '%s\n' "$N" |join -o 2.4 - plan/add-src+bin |sort -u | tr '\n' ' ')
	uploader="$(cat task/owner)"
	for id in $ids; do
		cat >"bugmail/$id" <<-__EOF
		From: ${GB_BUGZILLA_FROM}
		To: ${GB_BUGZILLA_TO}
		X-Bugzilla-In-Bug-Id: ${id}
		X-Bugzilla-In-Source-Package: ${N}
		X-Bugzilla-In-Binary-Packages: ${binaries}
		X-Bugzilla-In-Uploader: ${uploader}

		@bug_id=${id}
		@bug_status=RESOLVED
		@resolution=FIXED

		${N}-${EVR} -> ${repo}:

		${changelog}
		__EOF
		(echo "X-Bugzilla-In-Token: $GB_BUGZILLA_KEY"; cat "bugmail/$id") |/usr/sbin/sendmail -i -t
	done
done <plan/add-src
