#!/bin/sh -efu

. gb-sh-functions

id="$1"; shift
cd "$GB_TASKS_DIR/$id"

seq="$(cat task/seq)"
repo="$(cat task/repo)"
rc="$(cat task/rc)"
if [ "$rc" = 0 ]; then
	[ -f task/manual ] &&
		text=TESTED ||
		text=COMPLETE
else
	text=FAILED
fi
owner="$(cat task/owner)"
cc="$(set +f; sort -u gears/*/userid |join -v1 - task/owner)"

summary="$(cat task/summary)"
[ -n "$summary" ] || summary=' empty'
stripped_summary="$(printf %s "$summary" |fmt |head -n1)"
[ "$stripped_summary" = "$summary" ] ||
	stripped_summary="$stripped_summary ..."

try="$((1+$seq/3))"

. gb-sh-tmpdir

cat >"$tmpdir/draft" <<__EOF
To: git_$owner
Cc: $(printf %s "$cc" |sort |sed s/^/git_/ |tr -s '\n' , |sed 's/,/, /g')$GB_REPO_EMAIL
Reply-To: $owner@$GB_EMAIL_DOMAIN
Mail-Followup-To: $USER
X-girar-task-id: $id
X-girar-task-owner: $owner
X-girar-task-cc: $(printf %s "$cc" |tr -s '\n' , |sed 's/,/, /g')
X-girar-task-repo: $repo
X-girar-task-try: $try
X-girar-task-status: $text
X-girar-task-URL: $GB_SITE$GB_TASKS_DIR/$id/
__EOF

[ "$repo" != sisyphus ] ||
	repo=

[ $try -gt 1 ] || try=

[ "$stripped_summary" = "$summary" ] ||
	echo "X-girar-task-summary: [#$id]${repo:+ $repo} $text${try:+ (try $try)}$summary" >>"$tmpdir/draft"

echo "Subject: [#$id]${repo:+ $repo} $text${try:+ (try $try)}$stripped_summary" >>"$tmpdir/draft"

log_file="task/log${try:+.$try}"
log_size="$(du -bk "$log_file" |cut -f1)"

cat >>"$tmpdir/draft" <<__EOF

$GB_SITE$GB_TASKS_DIR/$id/$log_file

__EOF

if [ "$log_size" -le 128 ]; then
	cat -- "$log_file" >>"$tmpdir/draft"
fi

mutt -x -H "$tmpdir/draft" </dev/null
