#!/bin/sh -efu

. gb-sh-functions

# This check is for new binary packages only.
[ -s plan/add-bin ] ||
	exit 0

. gb-sh-tmpdir

for arch in $GB_ARCH; do
	$0-arch "$arch" ||
		stamp_echo "[$arch] install check FAILED" >>"$tmpdir"/FAIL &
done

wait

if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

# Do not stamp final OK because per-package install checks are already stamped.
exit 0
