#!/bin/sh -efu

. gb-sh-setup

id="$1"; shift
cd "$GB_TASKS/$id"

FAIL=`mktemp`

for arch in i586 x86_64; do
	$0-arch "$id" "$arch" ||
		echo "$arch build failed" >"$FAIL" &
	sleep 9
done

wait

if [ -s "$FAIL" ]; then
	cat >&2 "$FAIL"
	rm "$FAIL"
	exit 1
fi
rm "$FAIL"
