#!/bin/sh -efu

. gb-sh-functions
. gb-sh-girar-conf

RC=0

girar_check()
{
	local N="$1" i="$2"; shift 2
	local old
	if old=$(cd "$GB_REAL_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# real gear
		if ! (cd gears/$i/git && git describe "$old" >/dev/null); then
			echo >&2 "error: $N.git: not inherited"
			RC=1
		fi
	elif old=$(cd "$GB_SRPM_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# srpm gear
		if ! (cd gears/$i/git && git describe "$old" >/dev/null); then
			echo >&2 "error: $N.git: not inherited"
			RC=1
		fi
	else
		# fist-time push, no check
		:
	fi
}

while read -r N EVR F; do
	i=$(srpm2i "$F")
	girar_check "$N" "$i"
done <plan/add-src

exit $RC
