#!/bin/sh -efu

. gb-sh-setup
. gb-sh-hasher-functions

id="$1" arch="$2" i="$3"; shift 3
cd "$GB_TASKS/$id"

dir=$(cat gears/$i/dir)
tag_name=$(cat gears/$i/tag_name)
echo >&2 "build ${dir##*/} $tag_name for $arch"

hsh_dir=$(gb_hasher_dir "$arch")
hsh_num=$(gb_hasher_num "$arch")
hsh_aptconf=$(gb_hasher_aptconf "$arch")

rm -rf "$hsh_dir"/.gb
mkdir "$hsh_dir"/.gb

# Step 1: initialize and query hasher chroot.
hsh --target="$arch" --apt-config="$hsh_aptconf" --number="$hsh_num" \
	--mountpoints=/proc --nprocs=1 \
	--initroot -- "$hsh_dir" >"$hsh_dir"/.gb/out 2>&1 ||
		gb_task_fail "$id" "initroot failed: $(cat "$hsh_dir"/.gb/out)"

qf1='%{NAME} %|SERIAL?{%{SERIAL}:}|%{VERSION}-%{RELEASE}'
qf2='%{NAME}-%{VERSION}-%{RELEASE}.%|SOURCERPM?{%{ARCH}}:{src}|.rpm'
qf_id="$qf1\\t$qf2\\n"
hsh-run -- "$hsh_dir" rpmquery -a --qf="$qf_id" >"$hsh_dir"/.gb/chroot_base

# Step 2: build src.rpm (without sisyphus_check).
# This will also install all BuildRequires packages.
cat >"$hsh_dir"/.gb/save_srpm <<'EOF'
mkdir ~/SRPMS
cp -p --target-directory ~/SRPMS/ -- "$@"
EOF

hsh --target="$arch" --apt-config="$hsh_aptconf" --number="$hsh_num" \
	--mountpoints=/proc --nprocs=1 \
	--rebuild-prog="$hsh_dir"/.gb/save_srpm --no-sisyphus-check \
	--lazy-cleanup -- "$hsh_dir" gears/$i/pkg.tar >"$hsh_dir"/.gb/out 2>&1 ||
		gb_task_fail "$id" "cannot build src.rpm: $(cat "$hsh_dir"/.gb/out)"

srpm=$(set +f; echo "$hsh_dir"/chroot/usr/src/SRPMS/*.src.rpm) &&
	srpm_name=$(rpmquery --qf '%{NAME}' -p "$srpm") ||
	gb_task_fail "$id" "cannot build valid src.rpm"

# Step 3: examine BuildRequires.
hsh-run -- "$hsh_dir" rpmquery -a --qf="$qf_id" >"$hsh_dir"/.gb/chroot_BR
sort -o "$hsh_dir"/.gb/chroot_base -u "$hsh_dir"/.gb/chroot_base
sort -o "$hsh_dir"/.gb/chroot_BR -u "$hsh_dir"/.gb/chroot_BR
comm -23 "$hsh_dir"/.gb/chroot_BR "$hsh_dir"/.gb/chroot_base >"$hsh_dir"/.gb/chroot_BR+
mv -f "$hsh_dir"/.gb/chroot_BR+ "$hsh_dir"/.gb/chroot_BR

# Step 4: check if rebuild is needed at all.
if [ -s build/$i/$arch/chroot_base ]; then
	rm -f build/$i/$arch/REBUILD
	if ! diff -U1 build/$i/$arch/chroot_base "$hsh_dir"/.gb/chroot_base >"$hsh_dir"/.gb/out; then
		echo 1 >build/$i/$arch/REBUILD
		echo >>build/$arch/MERGE "chroot_base changed for ${dir##*/} $tag_name"
		cat >>build/$arch/MERGE <"$hsh_dir"/.gb/out
	fi
	if ! diff -U1 build/$i/$arch/chroot_BR "$hsh_dir"/.gb/chroot_BR >"$hsh_dir"/.gb/out; then
		echo 1 >build/$i/$arch/REBUILD
		echo >>build/$arch/MERGE "chroot_BR changed for ${dir##*/} $tag_name"
		cat >>build/$arch/MERGE <"$hsh_dir"/.gb/out
	fi
	# rebuild is still needed if previous packages has been rebuilt.
	for j in `seq 1 $(($i-1))`; do
		if [ -s build/$arch/$j/REBUILD ]; then
			rm -f build/$arch/$j/REBUILD
			echo 1 >build/$i/$arch/REBUILD
		fi
	done
	if ! [ -s build/$i/$arch/REBUILD ]; then
		(set +f; cp -p build/$i/$arch/rpms/*.rpm "$hsh_dir"/repo/$arch/RPMS.hasher/)
		[ $? -eq 0 ]
		echo >&2 "no need to rebuild ${dir##*/} $tag_name for $arch"
		exit 0
	fi
fi

# Step 5: examine repo/ contens.
for f in $(set +f; ls "$hsh_dir"/repo/SRPMS.hasher/*.rpm 2>/dev/null); do
	crc=$(sha1sum -b "$f" |head -c16)
	printf '%s\t%s\n' "${f##*/}" "${crc:?}"
done |sort >"$hsh_dir"/.gb/srpm1
for f in $(set +f; ls "$hsh_dir"/repo/$arch/RPMS.hasher/*.rpm 2>/dev/null); do
	crc=$(sha1sum -b "$f" |head -c16)
	printf '%s\t%s\n' "${f##*/}" "${crc:?}"
done |sort >"$hsh_dir"/.gb/rpms1

# Step 6: find out packager.
packager='Alexey Tourbin <at@altlinux.ru>'

# Step 7: build.
mkdir -p build/$i/$arch
hsh --target="$arch" --apt-config="$hsh_aptconf" --number="$hsh_num" \
	--mountpoints=/proc --nprocs=1 \
	--packager="$packager" -- "$hsh_dir" gears/$i/pkg.tar >build/$i/$arch/log 2>&1 ||
		gb_task_fail "$id" "cannot build $dir $tag_name: $(tail -33 build/$i/$arch/log)"

# Step 8: save results.
for f in $(set +f; ls "$hsh_dir"/repo/SRPMS.hasher/*.rpm 2>/dev/null); do
	crc=$(sha1sum -b "$f" |head -c16)
	printf '%s\t%s\n' "${f##*/}" "${crc:?}"
done |sort >"$hsh_dir"/.gb/srpm2
for f in $(set +f; ls "$hsh_dir"/repo/$arch/RPMS.hasher/*.rpm 2>/dev/null); do
	crc=$(sha1sum -b "$f" |head -c16)
	printf '%s\t%s\n' "${f##*/}" "${crc:?}"
done |sort >"$hsh_dir"/.gb/rpms2

comm -23 "$hsh_dir"/.gb/rpms{1,2} >"$hsh_dir"/.gb/out
if [ -s "$hsh_dir"/.gb/out ]; then
	# we are under attack: they try to replace previous packages
	gb_task_fail "$id" "${dir##*/} $tag_name bad intersections: $(cat "$hsh_dir"/.gb/out)"
fi
comm -23 "$hsh_dir"/.gb/srpm{1,2} >"$hsh_dir"/.gb/out
if [ -s "$hsh_dir"/.gb/out ]; then
	gb_task_fail "$id" "${dir##*/} $tag_name bad intersections: $(cat "$hsh_dir"/.gb/out)"
fi

comm -23 "$hsh_dir"/.gb/rpms{2,1} >"$hsh_dir"/.gb/out
if ! [ -s "$hsh_dir"/.gb/out ]; then
	gb_task_fail "$id" "${dir##*/} $tag_name produced no rpms"
fi
rm -rf build/$i/$arch/rpms
mkdir -p build/$i/$arch/rpms
tar -C "$hsh_dir"/repo/$arch/RPMS.hasher -cf - `cut -f1 "$hsh_dir"/.gb/out` |
tar -C build/$i/$arch/rpms -xf -

comm -23 "$hsh_dir"/.gb/srpm{2,1} >"$hsh_dir"/.gb/out
if ! [ -s "$hsh_dir"/.gb/out ]; then
	gb_task_fail "$id" "${dir##*/} $tag_name produced no srpm"
fi
rm -rf build/$i/$arch/srpm
mkdir -p build/$i/$arch/srpm
tar -C "$hsh_dir"/repo/SRPMS.hasher -cf - `cut -f1 "$hsh_dir"/.gb/out` |
tar -C build/$i/$arch/srpm -xf -

cp -p "$hsh_dir"/.gb/chroot_base build/$i/$arch/chroot_base
cp -p "$hsh_dir"/.gb/chroot_BR build/$i/$arch/chroot_BR

echo >&2 "build ${dir##*/} $tag_name for $arch OK"
