#!/bin/sh -efu

# This check does not apply to noarch packages.
cut -f3 plan/{add,rm}-bin |fgrep -qs -v noarch || exit 0

. gb-sh-functions
repo1="$GB_REPO_DIR"

# Reuse our temporary repo.
repo2="$TMPDIR/gb-repo-$GB_REPO_NAME"

. gb-sh-tmpdir
cd "$tmpdir"

for arch in i586 x86_64; do
	bad_elf_symbols_dircmp.pl {"$repo1","$repo2"}/$arch/RPMS.classic >$arch-bes.plus 3>$arch-bes.minus ||
		echo 1 >>FAIL &
done
wait
if [ -s FAIL ]; then
	exit 1
fi

rc=0 text=OK

for arch in i586 x86_64; do
	if [ -s $arch-bes.plus ]; then
		echo "	$arch: NEW bad_elf_symbols detected:"
		cat $arch-bes.plus
		rc=1 text=FAILED
	fi >&2
	if [ -s $arch-bes.minus ]; then
		echo "	$arch: old bad_elf_symbols resolved:"
		cat $arch-bes.minus
	fi >&2
done

if [ "$rc" = 1 ]; then
	# This list should include only proprietry binary drivers.
	cat >allow-bad-p <<'EOF'
^fglrx_glx-[[:digit:]][^[:space:]]+[[:space:]]+/usr/lib(64)?/X11/(fglrx/lib(dri|glx)|modules/drivers/fglrx_drv)\.so[[:space:]]
^nvidia_glx_[[:digit:]][^[:space:]]+[[:space:]]+/usr/lib(64)?/nvidia_[[:digit:]][^[:space:]/]+/[^[:space:]/]+\.so[[:space:]]
EOF
	egrep -qs -v -f allow-bad-p -- {i586,x86_64}-bes.plus ||
		rc=0 text=COND-OK
fi

stamp_echo >&2 "ELF symbols check $text"
exit $rc
