#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions

# Prepare remote node to build $arch packages for $GB_REPO_NAME repository.
rsync -a "$GB_HOME/remote/" "$remote_host:"
. shell-quote
ssh "$remote_host" ./gb-remote-plant "$GB_REPO_DIR" "$arch" \
	rpmargs="\"$(quote_shell "$GB_REPO_RPMARGS")\""

for i in $(src_nums); do
	$0-i "$arch" "$i"
done
