#!/bin/sh -efu

. gb-sh-girar-conf

srpm2i()
{
	local f="$1"; shift
	cd build
	set +f
	set -- [1-9]*/*/srpm/"$f"
	if ! [ -f "$1" ]; then
		echo " *** cannot find $f under build/"
		return 1
	fi >&2
	local IFS=/
	set -- $1
	echo "$1"
}

RC=0

girar_check()
{
	local N="$1" i="$2"; shift 2
	local old
	if old=$(cd "$GB_REAL_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# real gear
		if ! (cd gears/$i/git && git describe "$old" >/dev/null); then
			echo >&2 "error: $N.git: not inherited"
			RC=1
		fi
	elif old=$(cd "$GB_SRPM_GEARS"/"$N".git && git rev-parse "$GB_GEAR_BRANCH"); then
		# srpm gear
		if ! (cd gears/$i/git && git describe "$old" >/dev/null); then
			echo >&2 "error: $N.git: not inherited"
			RC=1
		fi
	else
		# cannot happen
		echo >&2 "error: $N.git is neither real nor srpm"
		RC=1
	fi
}

while read -r N EVR F; do
	i=$(srpm2i "$F")
	girar_check "$N" "$i"
done <plan/add-src

exit $RC
