#!/usr/bin/perl -n

#
# Accepts the following strings: opening parenthesis, then "Closes" or "ALT" or
# "ALT bug", then optional ":", then comma-separated list of bugs with optional
# '#' prepended, then closing parenthesis. Case-insensitive.
#

while($_ =~ s/\(\s*(?:closes|alt(?:\s*bug)?)\s*:?\s*(#?\s*\d+(?:\s*,\s*#?\s*\d+)*)\s*\)//i) {
  my $bugs = $1;
  while($bugs =~ s/.*?(\d+)//) {
    print "$1\n";
  }
}
