#!/bin/sh -efu

. gb-sh-functions

bloat=
if [ "$1" = '--bloat' ]; then
	bloat=1
	shift
fi

REPO_DIR="$1"
shift

. gb-sh-tmpdir
. gb-sh-rpmhdrcache

if [ -n "$bloat" ]; then
	# Temporary repo: disable bzip2, use 'xz --fast' mode.
	set -- --bloat --no-bz2 --xz
	export XZ_OPT='--fast'
else
	# Final repo: need to scan for useful files.
	for arch in $GB_ARCH noarch; do
		gb-x-useful-files "$REPO_DIR"/$arch/RPMS.classic >"$tmpdir"/useful-files.$arch ||
			echo 1 >>"$tmpdir"/FAIL &
	done
	wait
	if [ -s "$tmpdir"/FAIL ]; then
		exit 1
	fi
	set --
	for arch in $GB_ARCH noarch; do
		set -- "$@" "$tmpdir"/useful-files.$arch
	done
	LC_ALL=C sort -m -u -o "$tmpdir"/useful-files -- "$@"
	# Both bzip2 and xz should be enabled.
	set -- --useful-files="$tmpdir"/useful-files --no-scan \
		--changelog-since=2009-01-01 \
		--xz --bz2
	export XZ_OPT='--lzma2=nice=128,depth=80,lc=4'
fi

mkdir -p "$HOME"/.cache/gen{pkg,src}list

for arch in $GB_ARCH noarch; do
	[ -d "$REPO_DIR/$arch" ] || continue

	# Arch packages haven't changed?
	maybe_unchanged=
	if [ -z "$bloat" ] && ! cut -f3 plan/{add,rm}-bin |fgrep -qs "$arch"; then
		# But the result also depends on the list of useful-files,
		# which might have changed due to other architectures.
		maybe_unchanged='--maybe-unchanged'
	fi

	genbasedir "$@" $maybe_unchanged \
		--cachedir="$HOME"/.cache \
		--architectures="$GB_ARCH noarch" \
		--architecture="$arch" \
		--archive="${GB_REPO_ARCHIVE:-ALT Linux $GB_REPO_NAME}" \
		--codename="$GB_REPO_CODENAME" \
		--description="${GB_REPO_DESCRIPTION:-ALT Linux $GB_REPO_NAME}" \
		--label="${GB_REPO_LABEL:-$GB_REPO_NAME}" \
		--origin="${GB_REPO_ORIGIN:-ALT Linux Team}" \
		--suite="${GB_REPO_SUITE:-$GB_REPO_NAME}" \
		--version="${GB_REPO_VERSION:-$GB_REPO_NAME}" \
		-s --default-key="$GB_REPO_SIGNER" \
		--topdir="$REPO_DIR" \
		--flat --no-oldhashfile --bz2only --mapi \
		$arch ${GB_REPO_COMPONENT_NAMES:-classic} ||
			echo 1 >>"$tmpdir"/FAIL &
done
wait
if [ -s "$tmpdir"/FAIL ]; then
	exit 1
fi
