#!/bin/sh -eu

. gb-sh-functions

id="$1"; shift
cd "$GB_TASKS_DIR/index"


for index in */postponed; do
	[ -d "$index" ] || continue
	for i in "$index"/[1-9]*; do
		[ -d "$i/task" ] || continue
		# no locking yet
		sed -i "/^$id\$/d" "$i/task/depends" ||:
		[ ! -s "$i/task/depends" ] || continue
		(
			enable -f /usr/lib/bash/lockf lockf &&
			cd "$i" &&
			builtin lockf -n . &&
			gb-task-queue-rebuild
		)
	done
done
