#!/bin/sh -efu

REPO_DIR="$1"
shift

. gb-sh-conf
. gb-sh-tmpdir

for arch in $GB_ARCH noarch; do
	# Regen only if there are $arch packages.
	cut -f3 plan/{add,rm}-bin |fgrep -qs "$arch" ||
		continue
	gb-x-gen-ci $REPO_DIR/$arch/RPMS.classic >$tmpdir/$arch-ci &&
		mv -f $tmpdir/$arch-ci $REPO_DIR/$arch/base/contents_index ||
		stamp_echo "[$arch] FAILED to create contents_index" >> "$tmpdir"/FAIL &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

exit 0
