#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

for arch in $GB_ARCH; do
	$0-arch "$arch" "$@" ||
		stamp_echo "[$arch] ${0#gb-task-} FAILED" >>"$tmpdir"/FAIL &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

exit 0
