#!/bin/sh -efu

# Toplevel select-task/run-task loop.

signal=
trap 'signal=1' HUP INT QUIT PIPE TERM

(
	# Task sequence number must be updated consistently.
	trap '' HUP INT QUIT PIPE TERM
	id=$(gb-select-task)
	if [ -n "$id" ]; then
		echo >&2 -n "Running task $id ... "
		exec gb-run-task "$id"
	fi
)

trap - HUP INT QUIT PIPE TERM

if [ -n "$signal" ]; then
	echo >&2 'exiting due to pending signals'
	exit
fi

sleep 9

exec "$0"
