#!/bin/sh -efu

repo=/ALT/Sisyphus
logs=$PWD/logs/rebuild
meta=$PWD/meta

cd $TMPDIR

packages $repo/files/SRPMS >srpms
cut -f1,3 srpms |sort -u -k1,1 >src:N-F

for arch in i586 x86_64 noarch; do
	packages $repo/files/$arch/RPMS >$arch-rpms
	cut -f3 $arch-rpms |sort -u >$arch:F
	(cd $repo/files/$arch/RPMS
	 xargs -r rpmquery --qf '%{SOURCERPM}\n' -p ) <$arch:F >$arch:src_F
	n1=$(wc -l <$arch:F)
	n2=$(wc -l <$arch:src_F)
	[ $n1 = $n2 ]
	sed 's/\(.*\)-.*-.*/\1/' <$arch:src_F >$arch:src_N
	paste $arch:F $arch:src_N |sort -u >$arch:F-src_N
	sort -k2,2 -o $arch:F-src_N{,}
	join -t$'\t' -11 -22 src:N-F $arch:F-src_N -o '1.2 2.1' >$arch:src_F-F
	sort -u -o $arch:src_F-F{,}
done

sort -u -m {i586,x86_64,noarch}:src_F-F{,} >src_F-F
n1=$(wc -l <src_F-F)
sort -u -k2,2 -o src_F-F{,}
n2=$(wc -l <src_F-F)
[ $n1 = $n2 ]
perl -alne <src_F-F >srpm2rpms '
	push @{$srpm2rpms{$F[0]}}, $F[1];
	END { print "$_ @{$srpm2rpms{$_}}" for keys %srpm2rpms }'
sort -u -o srpm2rpms{,}

mkdir -p $meta
cd $meta
git init

while read -r srpm rpms; do
	src=$srpm
	src=${src%-*}
	src=${src%-*}
	rm -rf $src
	has_i586= has_x86_64= has_noarch=
	for rpm in $rpms; do
		case $rpm in
			*.i586.rpm) has_i586=i586 ;;
			*.x86_64.rpm) has_x86_64=x86_64 ;;
			*.noarch.rpm) has_noarch=noarch ;;
		esac
	done
	src_arches=
	if [ -n "$has_noarch" ]; then
		src_arches="i586 x86_64"
	else
		[ -n "$has_i586$has_x86_64" ]
		src_arches="$has_i586 $has_x86_64"
	fi
	mkdir -p $src/srpm
	rpmquery --qf '%|EPOCH?{%{EPOCH}:}|%{VERSION}-%{RELEASE}\n' -p $repo/files/SRPMS/$srpm >$src/srpm/EVR
	gb-x-rpm-changelog $repo/files/SRPMS/$srpm >$src/srpm/changelog
	for arch in $src_arches; do
		mkdir -p $src/srpm/$arch
		rpmquery -R -p $repo/files/SRPMS/$srpm >$src/srpm/$arch/BR
		sed -i '/^rpmlib(/d' $src/srpm/$arch/BR
		sed -i 's/ *$//' $src/srpm/$arch/BR
		sort -u -o $src/srpm/$arch/BR{,}
		log=$logs/$arch/$src.done.log.bz2
		if [ -f "$log" ]; then
			bzcat $log >$src/srpm/$arch/buildlog
			gb-x-fixup-buildlog $src/srpm/$arch/buildlog
		else
			echo >&2 "$log: file not found"
		fi
	done
	for rpm in $rpms; do
		arch=
		case $rpm in
			*.i586.rpm) arch=i586 ;;
			*.x86_64.rpm) arch=x86_64 ;;
			*.noarch.rpm) arch=noarch ;;
		esac
		[ -n "$arch" ]
		name=$rpm
		name=${name%-*}
		name=${name%-*}
		mkdir -p $src/rpms/$arch/$name
		rpmquery --qf '%|EPOCH?{%{EPOCH}:}|%{VERSION}-%{RELEASE}\n' -p $repo/files/$arch/RPMS/$rpm >$src/rpms/$arch/$name/EVR
		rpmquery --list -p $repo/files/$arch/RPMS/$rpm >$src/rpms/$arch/$name/F
		for q in requires provides obsoletes conflicts; do
			Q=$(echo $q |sed 's/\(.\).*/\U\1/')
			rpmquery --$q -p $repo/files/$arch/RPMS/$rpm >$src/rpms/$arch/$name/$Q
			sed -i 's/ *$//' $src/rpms/$arch/$name/$Q
			sort -u -o $src/rpms/$arch/$name/$Q{,}
		done
	done
done <$TMPDIR/srpm2rpms

git add .
git commit -m "${repo##*/} $(date +%Y%m%d)"
git repack -a -d
