#!/bin/sh -efu

export GIRAR_TASKS=$TMPDIR/girar-tasks
mkdir -p $GIRAR_TASKS/333
cd $GIRAR_TASKS/333

mkdir task
echo 333 >task/id
echo $USER >task/owner
echo sisyphus >task/repo

mkdir gears
i=0
for d; do
	tag=$(GIT_DIR="$d"/.git git describe --abbrev=0)
	i=$(($i+1))
	mkdir gears/$i
	cp -a "$d"/.git gears/$i/git
	echo "$d" >gears/$i/dir
	echo "$tag" >gears/$i/tag_name
done

set -x
gb-task-pkgtar 333
gb-task-build 333
gb-task-check-build 333
gb-task-repo-plan 333
gb-task-repo-vercheck 333
gb-task-repo-unmets 333
gb-task-check-acl 333

find build/ -type f |sort
