#!/bin/sh -efu

export GIRAR_TASKS=$TMPDIR/girar-tasks
mkdir -p $GIRAR_TASKS/333
cd $GIRAR_TASKS/333

mkdir task
echo 333 >task/id
echo $USER >task/owner
echo sisyphus >task/repo

mkdir gears
i=0
for d; do
	tag_name=$(GIT_DIR="$d"/.git git describe --abbrev=0)
	i=$(($i+1))
	mkdir gears/$i
	cp -a "$d"/.git gears/$i/git
	echo "$d" >gears/$i/dir
	echo "$tag_name" >gears/$i/tag_name
	tag_author=$(GIT_DIR="$d"/.git git cat-file tag "$tag_name" |sed -n '/^tagger /{s/^tagger //;s/>.*/>/p;q}')
	echo "$tag_author" >gears/$i/tag_author
done

set -x
gb-task-pkgtar
gb-task-build
gb-task-check-build
gb-task-repo-plan
gb-task-repo-vercheck
gb-task-repo-unmets
gb-task-check-acl
