#!/bin/sh -efu

. gb-sh-functions

id="$1"; shift

cd "$GB_TASKS_DIR/$id"
# obtain an exclusive lock on the TASKS structure
exec <.
flock 0

if [ "$(cat task/state)" != BUILDING ]; then
	echo >&2 "Task $id is not selected for build"
	exit 1
fi

try=$(cat task/try)
iter=$(cat task/iter)
log="logs/events.$try.$iter.log"
gb-task-set-summary

(umask 002 && > report/unmet-addressees > report/acl-addressees) || exit

$0-stages >>"$log" 2>&1 && rc=0 || rc=$?

state="$(cat task/state)"
case "$state" in
	POSTPONED) rc=1 ;;
	EPERM)
		if [ "$rc" = 0 ]; then
			rc=1
		else
			state=FAILED
		fi
		;;
	BUILDING)
		if [ "$rc" = 0 ]; then
			if [ -f task/swift ]; then
				state=SWEPT
			else
				state=TESTED
			fi
		else
			state=FAILED
		fi
		;;
	*)
		rc=1
		state=FAILED
		;;
esac

echo "$expected_task_version" > task/version

stamp_echo >>"$log" "task #$id for $GB_REPO_NAME $state"

if [ "$state" != TESTED -o -f task/test-only ]; then
	gb-x-girar task-change-state "$id" "$state"
	gb-task-send-email "$id"
	rm -f task/abort 2> /dev/null ||:
else
	gb-x-girar task-change-state "$id" PENDING
fi

exit $rc
