#!/bin/sh -efu

. gb-sh-functions

RC=0

while read -r N EVR A F P I dummy; do
	if py36_deps=$(rpmquery --requires --provides -p "$P" |
		grep -E '^(python3\.6|python = 3\.6|libpython3\.6)' )
	then
		echo >&2 $F: $py36_deps
		RC=1
	fi
done <plan/add-bin

if [ $RC -gt 0 ]; then
	stamp_echo >&2 'python3.6 dependencies are no longer allowed'
	stamp_echo >&2 'sorry for the inconvenience, please wait for python3.7 and try again later'
	exit 1
fi
