#!/bin/sh -efu

. gb-sh-functions

arch="$1"; shift
[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] || exit 0

comp=${GB_AREPO_COMPONENT_NAME:-classic}

RM()
{
	rm -v "$1"
}

CP()
{
	local src dst header rsrc
	src="$1"; shift
	dst="$1"; shift
	header="$(od -A n -N 4 -t x1 -- "$src")"
	if [ "$header" != ' ed ab ee db' ]; then
		echo "$src: unrecognized header: $header" >&2
		exit 1
	fi
	rsrc="$(readlink -ev -- "$src")"
	install -vpm444 -- "$rsrc" "$dst"
}

LN()
{
	local target link name dir deposited
	target="$1"; shift
	link="$1"; shift
	name="${target##*/}"

	[ -n "$name" ] && [ -n "$link" ] || return 0
	dir="$GB_SYMLINK_DIR/${name:0:2}/${name:2:2}"
	mkdir -p -- "$dir"
	deposited="$dir/$name"
	{
		flock 0
		[ -L "$deposited" ] ||
			ln -v -sn -- "$target" "$deposited"
	} < "$dir"
	ln -v -n -- "$deposited" "$link"
}

while read -r F; do
	RM $GB_REPO_DIR/$arch/RPMS.$comp/$F
	RM $GB_REPO_DIR/files/$arch/RPMS/$F
done < plan/arepo-rm-$arch >> logs/commit-$arch.log

while read -r N EVR F dummy; do
	CP arepo/$arch/rpms/$F $GB_REPO_DIR/files/$arch/RPMS/$F
	LN ../../files/$arch/RPMS/$F $GB_REPO_DIR/$arch/RPMS.$comp/$F
done < plan/arepo-add-$arch >> logs/commit-$arch.log

install -pm644 -- plan/arepo-table-$arch \
	"$GB_REPO_DIR/files/list/arepo-$arch.list"
install -pm644 -- plan/arepo-table-$arch.xz \
	"$GB_REPO_DIR/files/list/arepo-$arch.list.xz"

rsync -rlt arepo/$arch/base.bloat/ "$GB_REPO_DIR"/$arch/base.bloat/
rsync -rlt arepo/$arch/base/ "$GB_REPO_DIR"/$arch/base/

stamp_echo >&2 "[$arch] update OK"
