#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir
join -t$'\t' -o 1.1,1.2,1.3,1.4,1.5,2.3 plan/{add,rm}-src >$tmpdir/src
sort -t$'\t' -u -k1,3 -o $tmpdir/src{,} plan/add-src

# Drop old cvemails if any.
find mail/cvemail -type f -delete

while F0=; read -r N EVR F P I F0; do
	if [ -n "$F0" ]; then
		# Must be executed before commit-repo!
		srpm0=$GB_REPO_DIR/files/SRPMS/$F0
		changelog=$(rpm_changes_since "$P" "$srpm0")
	else
		changelog=$(rpm_recent_changes "$P")
	fi
	ids=$(printf '%s\n' "$changelog" |gb-x-parse-cves-from-changelog)
	[ -n "$ids" ] || continue
	stamp_echo >&2 "$N: fixes vulnerabilities: $ids"
	binaries=$(printf '%s\n' "$N" |join -o 2.4 - plan/add-src+bin |sort -u | tr '\n' ' ')
	uploader="$(cat task/owner)"
	for id in $ids; do
		cat >"mail/cvemail/$id" <<-__EOF
		From: ${GB_VULNZILLA_FROM}
		To: ${GB_VULNZILLA_TO}
		X-Vulnzilla-In-Vuln-Id: ${id}
		X-Vulnzilla-In-Source-Package: ${N}
		X-Vulnzilla-In-Binary-Packages: ${binaries}
		X-Vulnzilla-In-Uploader: ${uploader}
        X-Vulnzilla-In-Repo: ${GB_REPO_NAME}
        X-Vulnzilla-In-EVR: ${EVR}

		${changelog}
		__EOF
	done
done <$tmpdir/src
