#!/bin/sh -efu

state="$1"; shift
[ "$state" = pending ] || exit 0

. gb-sh-functions

[ -f plan/next.src.xz ] ||
	gb-task-queue-rebuild

[ -f task/version ] &&
	[ "$expected_task_version" = "$(head -c 8192 task/version)" ] ||
	gb-task-queue-rebuild

repo_cur="$(readlink -e -- "$GB_REPO_DIR")" &&
repo_prev="$(readlink -e -- build/repo/prev)" &&
[ "$repo_cur" = "$repo_prev" ] && exit ||
gb-task-queue-rebuild

exit 1
