#!/bin/sh -efu

# This should check that the build result is consistent on its own (sam
# po sebe).  This is NOT the right place to check if the build result is
# consistent with respect to a repo.

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

fail()
{
	printf '%s\n' "$*" >> $tmpdir/errors
}

# check each built package separately
for i in $(src_nums) $(copy_nums); do
	fail_if_task_abort_requested
	$0-i "$i" || fail "#$i"
done

# check all $arch packages in whole
for arch in $GB_ARCH; do
	fail_if_task_abort_requested
	$0-arch "$arch" || fail "$arch"
done

rc=0
if [ -f $tmpdir/errors ]; then
	rc=1
	text="FAILED for: $(sort -t'#' -k2,2n $tmpdir/errors |tr -s '\n' ' ')"
else
	text=OK
fi

stamp_echo >&2 "build check $text"
exit $rc
