#!/bin/sh -efu

# This should check that the build result is consistent on its own (sam
# po sebe).  This is NOT the right place to check if the build result is
# consistent with respect to a repo.

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

id="$(cat task/id)"

fail()
{
	printf '%s\n' "$*" >> $tmpdir/errors
}

task_started "$id"

# check each built package separately
for i in $(src_nums) $(copy_nums); do
	fail_if_task_abort_requested
	subtask_started "$id" "$i"
	if $0-i "$i"; then
		subtask_processed "$id" "$i"
	else
		subtask_failed "$id" "$i"
		fail "#$i"
	fi
done

# check all $arch packages in whole
for arch in $GB_ARCH; do
	fail_if_task_abort_requested
	task_started "$id" "$arch"
	if $0-arch "$arch"; then
		task_processed "$id" "$arch"
	else
		task_failed "$id" "$arch"
		fail "$arch"
	fi
done

rc=0
if [ -f $tmpdir/errors ]; then
	rc=1
	text="FAILED for: $(sort -t'#' -k2,2n $tmpdir/errors |tr -s '\n' ' ')"
	task_failed "$id"
else
	text=OK
	task_processed "$id"
fi

stamp_echo >&2 "build check $text"
exit $rc
