#!/bin/sh -efu

id="$(cat task/id)"
arch="$1"; shift

. gb-sh-functions

rm -rf "build/repo/$arch"

for i in $(src_nums); do
	$0-i "$arch" "$i"
	gb-x-girar hook-event subtask build "$id" "$i" "$arch" "$?" ||:
done
