#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

# Drop old bugmails if any.
find mail/bugmail -type f -delete

while read -r N EVR F P I; do
	changelog="build/$I/changelog"
	[ -s "$changelog" ] ||
		continue

	ids=$(gb-x-parse-bugs-from-changelog < "$changelog")
	[ -n "$ids" ] || continue
	stamp_echo >&2 "$N: closes bugs: $ids"
	binaries=$(printf '%s\n' "$N" |join -o 2.4 - plan/add-src+bin |sort -u | tr '\n' ' ')
	uploader="$(cat task/owner)"
	for id in $ids; do
		cat >"mail/bugmail/$id" <<-__EOF
		From: ${GB_BUGZILLA_FROM}
		To: ${GB_BUGZILLA_TO}
		X-Bugzilla-In-Bug-Id: ${id}
		X-Bugzilla-In-Source-Package: ${N}
		X-Bugzilla-In-Binary-Packages: ${binaries}
		X-Bugzilla-In-Uploader: ${uploader}

		@bug_id=${id}
		@bug_status=RESOLVED
		@resolution=FIXED

		${N}-${EVR} -> $GB_REPO_NAME:

		__EOF
		cat < "$changelog" >> "mail/bugmail/$id"
	done
done < plan/add-src
