#!/bin/sh -efu

. gb-sh-functions

case "${GB_DISABLE_CLOSE_BUGS-}" in
	1|[Yy][Ee][Ss]) exit 0 ;;
esac

# obtain a shared lock on the TASKS structure
exec <.
flock -s 0

dir=mail/bugmail

closed_bugs()
{
	find $dir -mindepth 1 -maxdepth 1 -name '[1-9]*' -type f -printf '%f\n' 2>/dev/null |
		sort -n
}

for id in $(closed_bugs); do
	(echo "X-Bugzilla-In-Token: $GB_BUGZILLA_KEY"; cat "$dir/$id") |
		/usr/sbin/sendmail -i -t
done
