#!/bin/sh -efu

. gb-sh-functions

# update src.hash
install -pm644 -- plan/src.hash.xz $GB_REPO_DIR/files/list/
rm -f -- $GB_REPO_DIR/files/list/src.hash

# update $arch.hash files
while read -r arch; do
	install -pm644 -- plan/$arch.hash.xz $GB_REPO_DIR/files/list/
	rm -f -- $GB_REPO_DIR/files/list/$arch.hash
done < plan/change-arch

# update arepo $arch.hash files
for arch in ${GB_AREPO_ARCH-}; do
	[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] ||
		continue
	install -pm644 -- plan/$arch.hash.xz $GB_REPO_DIR/files/list/
	rm -f -- $GB_REPO_DIR/files/list/$arch.hash
done
