#!/bin/sh -efu

. gb-sh-functions

case "${GB_DISABLE_REPORT_VULNS-}" in
	1|[Yy][Ee][Ss]) exit 0 ;;
esac

# obtain a shared lock on the TASKS structure
exec <.
flock -s 0

dir=mail/cvemail

fixed_vulns()
{
	find $dir -mindepth 1 -maxdepth 1 -name '[1-9a-zA-Z]*' -type f 2>/dev/null |
		sort -u
}

for file in $(fixed_vulns); do
	(echo "X-Vulnzilla-In-Token: $GB_VULNZILLA_KEY"; cat "$file") |
		/usr/sbin/sendmail -i -t
done
