#!/bin/sh -efu

state="$1"; shift
[ "$state" = pending ] || exit 0

. gb-sh-functions

[ -z "$(img_nums)" ] ||
	exit 1

next_b=build/repo/noarch/base.next
next_bb=build/repo/noarch/base.bloat.next
[ -f plan/next.src.xz ] &&
[ -f "$next_b"/release -o -f "$next_b"/unchanged ] &&
[ -f "$next_bb"/release -o -f "$next_bb"/unchanged ] || {
	gb-task-queue-rebuild
	exit 1
}

if [ "$GB_REPO_OPT_BLAKE2B" != '--no-blake2b' ]; then
	[ -f "$next_b"/unchanged ] || grep -qx 'BLAKE2b:' "$next_b"/release || {
		gb-task-queue-rebuild
		exit 1
	}
fi

[ -f task/version ] &&
	[ "$expected_task_version" = "$(head -c 8192 task/version)" ] || {
	gb-task-queue-rebuild
	exit 1
}

repo_cur="$(readlink -e -- "$GB_REPO_DIR")" &&
repo_prev="$(readlink -e -- build/repo/prev)" &&
[ "$repo_cur" = "$repo_prev" ] || {
	gb-task-queue-rebuild
	exit 1
}

exit 0
