#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

# This check is for new binary packages only.
[ -s plan/add-bin ] ||
	exit 0

. gb-sh-tmpdir

id="$(cat task/id)"

task_started "$id"
for arch in ${GB_CHECK_INSTALL_ARCH:-$GB_ARCH}; do
	task_started "$id" "$arch"
	if $0-arch "$arch"; then
		task_processed "$id" "$arch"
	else
		stamp_echo "[$arch] install check FAILED" >>"$tmpdir"/FAIL
		task_change_state_to_failing "[$arch]"
		task_failed "$id" "$arch"
	fi &
done

wait

if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	if is_check_failure_tolerated; then
		echo >&2 "The most essential install check failed, but \`$GB_REPO_NAME' is so neglected a repository that nobody cares about such trifles as this."
		task_ignored "$id"
		exit 0
	fi
	task_failed "$id"
	exit 1
fi

task_processed "$id"

# Do not stamp final OK because per-package install checks are already stamped.
exit 0
