#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

id="$(cat task/id)"

fail()
{
	stamp_echo >&2 "[$arch] arepo save FAILED"
	task_failed "$id"
	exit 1
}

task_started "$id"

for arch in ${GB_AREPO_ARCH-}; do
	[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] || continue
	(umask 002; mkdir -p arepo/$arch/base) || fail
	rsync -rlt --exclude='ds.*' "$GB_AREPO_DIR/$arch/base/" arepo/$arch/base/ || fail
	(umask 002; mkdir -p arepo/$arch/base.bloat) || fail
	rsync -rlt "$GB_AREPO_DIR/$arch/base.bloat/" arepo/$arch/base.bloat/ || fail
done

task_processed "$id"

#stamp_echo >&2 'arepo save OK'
