#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

id="$1"; shift

rm -rf build/repo/noarch

for arch in $GB_ARCH; do
	rm -rf "build/repo/$arch"
	(
		umask 002
		mkdir -p "build/repo/$arch/base" "build/repo/$arch/RPMS.task"
	) || exit
done

while read -r N EVR A F P I C dummy; do
	case "$A" in
		noarch)
			link=
			for arch in $GB_ARCH; do
				if [ -n "$link" ]; then
					ln -n -- "$link" \
						"build/repo/$arch/RPMS.task/"
				else
					ln -rsn -- "$P" \
						"build/repo/$arch/RPMS.task/"
					link="build/repo/$arch/RPMS.task/$F"
				fi
			done
			;;
		*)
			ln -rsn -- "$P" "build/repo/$A/RPMS.task/"
			;;
	esac
done < plan/add-bin

GB_REPO_COMPONENT_NAMES=task GB_REPO_ARCHIVE="task $id" GB_REPO_DESCRIPTION="task $id" GB_REPO_LABEL="task $id" GB_REPO_SUITE="task $id" GB_REPO_VERSION="task $id" \
	gb-y-repo-regen-basedir --bloat build/repo

#stamp_echo >&2 'task repo generation OK'
