#!/bin/sh -efu

enable -f /usr/lib/bash/lockf lockf
# obtain a shared lock on the TASKS structure
builtin lockf -sv .

. gb-sh-functions

dir=mail/bugmail

closed_bugs()
{
	find $dir -mindepth 1 -maxdepth 1 -name '[1-9]*' -type f -printf '%f\n' 2>/dev/null |
		sort -n
}

for id in $(closed_bugs); do
	(echo "X-Bugzilla-In-Token: $GB_BUGZILLA_KEY"; cat "$dir/$id") |
		/usr/sbin/sendmail -i -t
done
