#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions

rm -rf "build/repo/$arch"

for i in $(src_nums); do
	$0-i "$arch" "$i" || {
		rc=$?
		# force rebuild packages on the task run
		touch "build/$i/force-rebuild"
		exit $rc
	}
done
