#!/bin/sh -efu

. gb-sh-functions

arch="$1"; shift

comp=${GB_AREPO_COMPONENT_NAME:-classic}

topdir=$GB_AREPO_DIR/$arch
mkdir $topdir
mkdir $topdir/base
# copy directory structure (using symlinks)
if [ -d $GB_REPO_DIR/$arch/RPMS.$comp ]; then
	cp -prs $GB_REPO_DIR/$arch/RPMS.$comp $topdir/
else
	mkdir $topdir/RPMS.$comp
fi

while read -r F; do
	rm -- $topdir/RPMS.$comp/$F
done < plan/arepo-rm-$arch

while read -r dummy dummy F dummy; do
	ln -s $PWD/arepo/$arch/rpms/$F $topdir/RPMS.$comp/
done < plan/arepo-add-$arch

gb-y-arepo-genbasedir-arch $arch $GB_AREPO_DIR

stamp_echo >&2 "[$arch] created next repo"
