#!/bin/sh -efu

. gb-sh-functions

set -- $(userid_nums)
if [ $# -eq 0 ]; then
	echo empty task
	exit 1
fi

if [ -s task/message ]; then
	stamp_echo "message: $(tr -cd '[:print:]' < task/message)"
fi

for i; do
	printf '#%d ' "$i"
	if [ -s "gears/$i/dir" ]; then
		printf 'build %s from %s' "$(cat "gears/$i/tag_name")" "$(cat "gears/$i/dir")"
		pkg_tar="gears/$i/pkg.tar"
		if [ -s "$pkg_tar" ]; then
			printf ' fetched at %s' \
				"$(LC_TIME=C date -u -r "$pkg_tar" '+%Y-%b-%d %T')"
		fi
		if [ -s "gears/$i/rebuild_from" ]; then
			printf ' from %s' "$(cat "gears/$i/rebuild_from")"
		fi
	elif [ -s "gears/$i/srpm" ]; then
		printf 'build %s' "$(cat "gears/$i/srpm")"
		if [ -s "gears/$i/rebuild_from" ]; then
			printf ' from %s' "$(cat "gears/$i/rebuild_from")"
		fi
	elif [ -s "gears/$i/package" ]; then
		package="$(cat "gears/$i/package")"
		if [ -s "gears/$i/copy_repo" ]; then
			printf 'copy %s from %s' "$package" "$(cat "gears/$i/copy_repo")"
		else
			printf 'delete %s' "$package"
		fi
	else
		printf %s removed
	fi
	echo
done
