#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

# Drop old cvemails if any.
find mail/cvemail -type f -delete

while read -r N EVR F P I; do
	changelog="build/$I/changelog"
	[ -s "$changelog" ] ||
		continue

	mentioned_ids=$(gb-x-parse-mentioned-vulns-from-changelog < "$changelog")
	[ -n "$mentioned_ids" ] || continue
	fixed_ids=$(gb-x-parse-vulns-from-changelog < "$changelog")
	binaries=$(printf '%s\n' "$N" |join -o 2.4 - plan/add-src+bin |sort -u | tr '\n' ' ')
	uploader="$(cat task/owner)"
	truly_mentioned=

	for id in $mentioned_ids; do
		if printf ' %s \n' $fixed_ids | grep -q " $id "; then
			in_type='Fix'
		else
			truly_mentioned="$truly_mentioned $id"
			in_type='Mention'
		fi

		{
			cat <<-__EOF
			From: ${GB_VULNZILLA_FROM}
			To: ${GB_VULNZILLA_TO}

			X-Vulnzilla-In-Vuln-Id: ${id}
			X-Vulnzilla-In-Source-Package: ${N}
			X-Vulnzilla-In-Binary-Packages: ${binaries}
			X-Vulnzilla-In-Uploader: ${uploader}
			X-Vulnzilla-In-Repo: ${GB_REPO_NAME}
			X-Vulnzilla-In-EVR: ${EVR}
			X-Vulnzilla-In-Type: ${in_type}

			__EOF
			cat -- "${changelog}"
		} > "mail/cvemail/$id"
	done

	[ -z "$fixed_ids" ] || stamp_echo >&2 "$N: fixes vulnerabilities: $fixed_ids"
	[ -z "$truly_mentioned" ] || stamp_echo >&2 "$N: mentions vulnerabilities:$truly_mentioned"
done < plan/add-src
