#!/bin/sh -efu

id="$(cat task/id)"
arch="$1"; shift

. gb-sh-functions

rm -rf "build/repo/$arch"

for i in $(src_nums); do
	subtask_started "$id" "$i" "$arch"
	if $0-i "$arch" "$i"; then
		subtask_processed "$id" "$i" "$arch"
	else
		subtask_failed "$id" "$i" "$arch"
		exit 1
	fi
done
