#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

id="$(cat task/id)"
rc=0
text=OK

task_started "$id"

for i in $(src_nums) $(copy_nums); do
	fail_if_task_abort_requested
	subtask_started "$id" "$i"
	if $0-i "$i"; then
		subtask_processed "$id" "$i"
	else
		if is_check_failure_tolerated; then
			text=IGNORED
			subtask_ignored "$id" "$i"
		else
			rc=1
			text=FAILED
			subtask_failed "$id" "$i"
		fi
	fi
done

stamp_echo >&2 "noarch check $text"

if [ "$rc" = 0 ]; then
	task_processed "$id"
else
	task_failed "$id"
fi

exit $rc
