#!/bin/sh -efu

arch="$1" i="$2"; shift 2

[ -d "build/$i/$arch/rpms/" ] || exit 0

. gb-sh-functions

gb-x-rsync-loop -qrlt --delete -- "build/$i/$arch/rpms/" "$remote_host:build/rpms/"
gb-x-ssh "$remote_host" ./gb-remote-copy-packages "$arch"
