#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir
join -t$'\t' -o 1.1,1.2,1.3,1.4,1.5,2.3 plan/{add,rm}-src >$tmpdir/src
sort -t$'\t' -u -k1,3 -o $tmpdir/src{,} plan/add-src

# Drop old bugmails if any.
find bugmail -type f -delete

while F0=; read -r N EVR F P I F0; do
	if [ -n "$F0" ]; then
		# Must be executed before commit-repo!
		srpm0=$GB_REPO_DIR/files/SRPMS/$F0
		changelog=$(rpm_changes_since "$P" "$srpm0")
	else
		changelog=$(rpm_recent_changes "$P")
	fi
	ids=$(printf '%s\n' "$changelog" |gb-x-parse-bugs-from-changelog)
	[ -n "$ids" ] || continue
	stamp_echo >&2 "$N: closes bugs: $ids"
	binaries=$(printf '%s\n' "$N" |join -o 2.4 - plan/add-src+bin |sort -u | tr '\n' ' ')
	uploader="$(cat task/owner)"
	for id in $ids; do
		cat >"bugmail/$id" <<-__EOF
		From: ${GB_BUGZILLA_FROM}
		To: ${GB_BUGZILLA_TO}
		X-Bugzilla-In-Bug-Id: ${id}
		X-Bugzilla-In-Source-Package: ${N}
		X-Bugzilla-In-Binary-Packages: ${binaries}
		X-Bugzilla-In-Uploader: ${uploader}

		@bug_id=${id}
		@bug_status=RESOLVED
		@resolution=FIXED

		${N}-${EVR} -> $GB_REPO_NAME:

		${changelog}
		__EOF
	done
done <$tmpdir/src
