#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir
join -t$'\t' -o 1.1,1.2,1.3,1.4,1.5,2.3 plan/{add,rm}-src > $tmpdir/src
sort -t$'\t' -u -k1,3 -o $tmpdir/src{,} plan/add-src

while F0=; read -r N EVR F P I F0; do
	if [ -n "$F0" ]; then
		# Must be executed before commit-repo!
		srpm0="$GB_REPO_DIR/files/SRPMS/$F0"
		rpm_changes_since "$P" "$srpm0"
	else
		rpm_recent_changes "$P"
	fi < /dev/null > "build/$I/changelog"
done < $tmpdir/src
