#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

id="$(cat task/id)"

task_started "$id"
gb-x-girar check-task-perms "$id" && rc=0 || rc=1

if [ "$rc" = 0 ]; then
	text=OK
	task_processed "$id"
elif [ -f task/test-only ]; then
	text=IGNORED
	task_ignored "$id"
else
	text=FAILED
	task_failed "$id"
	gb-x-girar task-change-state "$id" EPERM
fi

stamp_echo >&2 "acl check $text"
