#!/bin/sh -efu

. gb-sh-functions

prev_repo_dir="$(readlink -ev -- "$GB_REPO_DIR")"
task_id=$(cat task/id)
next_repo_dir="$GB_REPO_ROOT/$GB_REPO_NAME/release/$task_id"

if [ -d "$next_repo_dir" ]; then
	stamp_echo >&2 "$next_repo_dir already exists!"
	exit 1
fi
cp -al -- "$prev_repo_dir" "$next_repo_dir"
stamp_echo >&2 'repo clone OK'

GB_REPO_DIR="$next_repo_dir"
export GB_REPO_DIR

gb-y-task-commit-packages "$GB_REPO_DIR" > logs/commit.log
stamp_echo >&2 'packages update OK'

# Update lists.
install -pm644 -- plan/next.src "$GB_REPO_DIR/files/list/src.list"
install -pm644 -- plan/next.bin "$GB_REPO_DIR/files/list/bin.list"
install -pm644 -- plan/next.src.xz "$GB_REPO_DIR/files/list/src.list.xz"
install -pm644 -- plan/next.bin.xz "$GB_REPO_DIR/files/list/bin.list.xz"

# Reuse base directories from our prepared repo.
updated=
for arch in $GB_ARCH noarch; do
	repo_base="$GB_REPO_DIR/$arch/base"
	next_base="build/repo/$arch/base.next"
	cmp_file=pkglist.classic.xz
	# If $cmp_file has not changed, skip the update for this $arch.
	if cmp -s "$repo_base/$cmp_file" "$next_base/$cmp_file"; then
		continue
	fi
	# NB: no --delete here, contents_index might be optimized out.
	rsync -rlt "$next_base"/ "$repo_base"/
	updated="$updated $arch"
done

stamp_echo >&2 "[${updated## }] update OK"

gb-task-commit-arepo
gb-task-commit-repo-hash

task_info="$GB_REPO_DIR/files/list/task.info"
rm -f -- "$task_info"
cat > "$task_info" <<EOF
task $task_id
prev ${prev_repo_dir##*/}
EOF
date_s="$(date -r "$task_info" +%s)"

stamp_echo >&2 'repo update OK'

reposited="$(gb-y-reposit-task "$GB_REPO_NAME" "$task_id")"
expected="$(readlink -ev -- "$GB_REPO_ROOT/$GB_REPO_NAME/task/$task_id")"
if [ "$reposited" != "$expected" ]; then
	stamp_echo >&2 "expected $expected, reposited $reposited!"
	exit 1
fi

chmod u+w -- "$next_repo_dir"
rm -rf -- "$next_repo_dir"

latest="$GB_REPO_ROOT/$GB_REPO_NAME/release/latest"
ln -snf -- "../task/$task_id" "$latest.$task_id"
readlink -ev -- "$latest.$task_id" > /dev/null
mv -fT -- "$latest.$task_id" "$latest"

# update index dirs
index_dir="$GB_REPO_ROOT/$GB_REPO_NAME/index"
echo "$task_id" >> "$index_dir/task.list"

for type in src; do
	mkdir -p -- "$index_dir/$type"
	while read -r N EVR I; do
		sym="$(printf %s "$N" |cut -c1)"
		dir="$index_dir/$type/$sym/$N"
		# sid is not defined for non-build methods
		if [ -f gears/$I/sid ]; then
			sid="$(cat gears/$I/sid)"
		else
			sid=
		fi
		mkdir -p -- "$dir"
		touch -- "$dir"
		printf '%s\t%s\t%s\t%s\t%s\n' \
			"$date_s" "$task_id" "$I" "$EVR" "$sid" \
			>> "$dir/d-t-s-evr.list"
		gb-y-print-rip-html "$GB_REPO_NAME" "$N" \
			"$dir/d-t-s-evr.list" > "$dir/index.html" ||:
	done < plan/rip-$type
done

sync &
stamp_echo >&2 'repo save OK'
