#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

id="$1"; shift

rm -rf build/repo/noarch

for arch in $GB_ARCH; do
	rm -rf "build/repo/$arch"
	(
		umask 002
		mkdir -p "build/repo/$arch/base" "build/repo/$arch/RPMS.task"
	) || exit
done

while read -r N EVR A F P I C dummy; do
	case "$A" in
		noarch)
			link=
			for arch in $GB_ARCH; do
				if [ -n "$link" ]; then
					ln -n -- "$link" \
						"build/repo/$arch/RPMS.task/"
				else
					ln -rsn -- "$P" \
						"build/repo/$arch/RPMS.task/"
					link="build/repo/$arch/RPMS.task/$F"
				fi
			done
			;;
		*)
			ln -rsn -- "$P" "build/repo/$A/RPMS.task/"
			;;
	esac
done < plan/add-bin

mkdir -p "$HOME"/.cache/gen{pkg,src}list

date_s="$(date +%s)"

. gb-sh-tmpdir

for arch in $GB_ARCH; do
	[ -d "build/repo/$arch" ] || {
		> "$tmpdir/OK-$arch"
		continue
	}

	# Temporary repo: disable bzip2, use 'xz --fast' mode.
	export XZ_OPT='--fast'
	genbasedir --bloat --xz --no-bz2 \
		--cachedir="$HOME"/.cache \
		--architecture="$arch" \
		--architectures="$GB_ARCH noarch" \
		--archive="task $id" \
		--codename="${GB_REPO_CODENAME:-$date_s}" \
		--description="task $id" \
		--label="task $id" \
		--origin="${GB_REPO_ORIGIN:-ALT Linux Team}" \
		--suite="task $id" \
		--version="${GB_REPO_VERSION:-$date_s}" \
		-s --default-key="$GB_INDEX_SIGNER" \
		--topdir="build/repo" \
		--flat --no-oldhashfile --compressedonly --mapi \
		$arch task &&
			> "$tmpdir/OK-$arch" &
done
wait

check_and_clear_OK_flags "$tmpdir"/OK $GB_ARCH
