#!/bin/sh -efu

arch="$1"; shift
id="$1"; shift

. gb-sh-functions

topdir=build/repo
rm -rf $topdir/$arch
[ -s plan/arepo-add-$arch ] || exit 0
umask 002
mkdir -p $topdir/$arch/base
mkdir -p $topdir/$arch/RPMS.task

while read -r dummy dummy F dummy; do
	ln -s ../../../../arepo/$arch/rpms/$F $topdir/$arch/RPMS.task/
done < plan/arepo-add-$arch

mkdir -p "$HOME"/.cache/gen{pkg,src}list

date_s="$(date +%s)"

# Temporary repo: disable bzip2, use 'xz --fast' mode.
export XZ_OPT='--fast'
genbasedir --bloat --xz --no-bz2 \
	--cachedir="$HOME"/.cache \
	--architecture="$arch" \
	--architectures="$arch" \
	--archive="task $id" \
	--codename="${GB_REPO_CODENAME:-$date_s}" \
	--description="task $id" \
	--label="task $id" \
	--origin="${GB_REPO_ORIGIN:-ALT Linux Team}" \
	--suite="task $id" \
	--version="${GB_REPO_VERSION:-$date_s}" \
	-s --default-key="$GB_INDEX_SIGNER" \
	--topdir="$topdir" \
	--flat --no-oldhashfile --mapi --compressedonly \
	$arch task
