#!/bin/sh -efu

. gb-sh-functions

arch="$1"; shift
[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] || exit 0

comp=${GB_AREPO_COMPONENT_NAME:-classic}

RM()
{
	rm -v "$1"
}

CP()
{
	local deposited
	deposited=$(gb-y-deposit-file "$1")
	ln -v -- "$deposited" "$2"
	ln -v -snf -- "$deposited" "$1"
}

LN()
{
	ln -v -s "$1" "$2"
}

while read -r F; do
	RM $GB_REPO_DIR/$arch/RPMS.$comp/$F
	RM $GB_REPO_DIR/files/$arch/RPMS/$F
done < plan/arepo-rm-$arch >> logs/commit-$arch.log

while read -r N EVR F dummy; do
	CP arepo/$arch/rpms/$F $GB_REPO_DIR/files/$arch/RPMS/$F
	LN ../../files/$arch/RPMS/$F $GB_REPO_DIR/$arch/RPMS.$comp/$F
done < plan/arepo-add-$arch >> logs/commit-$arch.log

install -pm644 -- plan/arepo-table-$arch \
	"$GB_REPO_DIR/files/list/arepo-$arch.list"
install -pm644 -- plan/arepo-table-$arch.xz \
	"$GB_REPO_DIR/files/list/arepo-$arch.list.xz"

rsync -rlt arepo/$arch/base/ "$GB_REPO_DIR"/$arch/base/

stamp_echo >&2 "[$arch] update OK"
