#!/bin/sh -efu

set -o pipefail

LANG=C
LC_ALL=C
export LANG LC_ALL

repo="$1"; shift
basedir="$1"; shift
qf="$1"; shift

[ $# -gt 0 ] ||
	set -- $(set +f && cd "$repo" && ls -d RPMS.?* | sed 's/^RPMS\.//')

for comp; do
	[ -f "$repo/$basedir/pkglist.$comp" ] || continue
	pkglist-query "$qf" "$repo/$basedir/pkglist.$comp"
done |
	sort -u
