#!/bin/sh -efu

. gb-sh-functions

REPO_DIR="$1"
shift

RM()
{
	rm -v "$1"
}

CP()
{
	local src dst header rsrc
	src="$1"; shift
	dst="$1"; shift
	header="$(od -A n -N 4 -t x1 -- "$src")"
	if [ "$header" != ' ed ab ee db' ]; then
		echo "$src: unrecognized header: $header" >&2
		exit 1
	fi
	rsrc="$(readlink -ev -- "$src")"
	install -vpm444 -- "$rsrc" "$dst"
}

LN()
{
	local target link name deposited
	target="$1"; shift
	link="$1"; shift
	name="${target##*/}"

	[ -n "$name" ] && [ -n "$link" ] || return 0;
	deposited="$GB_SYMLINK_DIR/$name"
	{
		flock 0
		[ -L "$deposited" ] ||
			ln -v -sn -- "$target" "$deposited"
	} < "$GB_SYMLINK_DIR"
	ln -v -n -- "$deposited" "$link"
}

guess_comp()
{
	local name dir path
	name="$1"; shift
	dir="$1"; shift

	comp=classic
	if [ -z "${name##*-gostcrypto-*}" ]; then
		comp=gostcrypto
		return
	fi
	for c in checkinstall debuginfo gostcrypto; do
		if [ -z "${name##*-$c}" ]; then
			path="$dir/RPMS.$c"
			if [ -d "$path" ]; then
				comp=$c
			else
				echo "warning: $path does not exist, falling back to 'classic' component" >&2
			fi
			break
		fi
	done
}

while read -r N EVR A F; do
	guess_comp "$N" "$REPO_DIR/$A"
	pkg=$REPO_DIR/$A/RPMS.$comp/$F
	[ -f "$pkg" ] ||
		pkg=$REPO_DIR/$A/RPMS.classic/$F
	RM "$pkg"
	RM $REPO_DIR/files/$A/RPMS/$F
done < plan/rm-bin

while read -r N EVR A F P I; do
	guess_comp "$N" "$REPO_DIR/$A"
	CP "$P" $REPO_DIR/files/$A/RPMS/$F
	LN ../../files/$A/RPMS/$F $REPO_DIR/$A/RPMS.$comp/$F
done < plan/add-bin

while read -r F A; do
	RM $REPO_DIR/$A/SRPMS.classic/$F
done < plan/rm-srpm2arch

while read -r N EVR F; do
	RM $REPO_DIR/files/SRPMS/$F
done < plan/rm-src

while read -r N EVR F P I; do
	CP "$P" $REPO_DIR/files/SRPMS/$F
done < plan/add-src

while read -r F P A; do
	LN ../../files/SRPMS/$F $REPO_DIR/$A/SRPMS.classic/$F
done < plan/add-srpm2arch
