#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

id="$(cat task/id)"
gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:

for arch in $GB_AREPO_ARCH; do
	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" "$arch" ||:
	if $0-arch "$arch" "$@"; then
		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" "$arch" ||:
	else
		me=${0##*/}
		stamp_echo "[$arch] ${me#gb-task-arepo-} FAILED" >>"$tmpdir"/FAIL
		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" "$arch" ||:
	fi &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
	exit 1
fi

gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:

exit 0
