#!/bin/sh -efu

. gb-sh-functions

cd "$GB_TASKS_DIR/.archived"

[ -d ../.done ] ||
	exit 0

set -- $(set +f && ls -d $GB_REPO_ROOT/*/task/.archived)

for task in $(set +f && ls -d [1-9]*); do
	[ -d "$task" ] || continue
	for d; do
		if [ -d "$d/$task" ]; then
			continue 2
		fi
	done
	owner="$(stat -c %U "$task")"
	owner="${owner#git_}"
	dir="../.done/$owner"
	[ -d "$dir" ] || continue
	mv "$task" "$dir/"
	logger -t "${0##*/}" "done: task=$task owner=$owner"
done
