#!/bin/sh -efu

. gb-sh-functions

REPO_DIR="$1"
shift

RM()
{
	rm -v "$1"
}

CP()
{
	local src dst header rsrc
	src="$1"; shift
	dst="$1"; shift
	header="$(od -A n -N 4 -t x1 -- "$src")"
	if [ "$header" != ' ed ab ee db' ]; then
		echo "$src: unrecognized header: $header" >&2
		exit 1
	fi
	rsrc="$(readlink -ev -- "$src")"
	install -vpm444 -- "$rsrc" "$dst"
}

LN()
{
	local target link name dir deposited
	target="$1"; shift
	link="$1"; shift
	name="${target##*/}"

	[ -n "$name" ] && [ -n "$link" ] || return 0
	dir="$GB_SYMLINK_DIR/${name:0:2}/${name:2:2}"
	mkdir -p -- "$dir"
	deposited="$dir/$name"
	{
		flock 0
		[ -L "$deposited" ] ||
			ln -v -sn -- "$target" "$deposited"
	} < "$dir"
	ln -v -n -- "$deposited" "$link"
}

while read -r N EVR A F C dummy; do
	pkg=$REPO_DIR/$A/RPMS.$C/$F
	[ -f "$pkg" ] ||
		pkg=$REPO_DIR/$A/RPMS.classic/$F
	RM "$pkg"
	RM $REPO_DIR/files/$A/RPMS/$F
done < plan/rm-bin

while read -r N EVR A F P I C dummy; do
	CP "$P" $REPO_DIR/files/$A/RPMS/$F
	LN ../../files/$A/RPMS/$F $REPO_DIR/$A/RPMS.$C/$F
done < plan/add-bin

while read -r F A; do
	RM $REPO_DIR/$A/SRPMS.classic/$F
done < plan/rm-srpm2arch

while read -r N EVR F; do
	RM $REPO_DIR/files/SRPMS/$F
done < plan/rm-src

while read -r N EVR F P I; do
	CP "$P" $REPO_DIR/files/SRPMS/$F
done < plan/add-src

while read -r F P A; do
	LN ../../files/SRPMS/$F $REPO_DIR/$A/SRPMS.classic/$F
done < plan/add-srpm2arch
