#!/bin/sh -eu

. gb-sh-functions

dep="$1"; shift
cd "$GB_TASKS_DIR/index"

for index in */postponed; do
	[ -d "$index" ] || continue
	for dir in "$index"/[1-9]*; do
		[ -f "$dir/task/depends" ] ||
			continue
		$0-dir "$dep" "$dir" ||:
	done
done
