#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

id="$(cat task/id)"
gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:

for arch in $GB_ARCH; do
	$0-arch "$arch" "$@" || {
		me=${0##*/}
		prefix="[$arch] ${me#gb-task-}"
		stamp_echo "$prefix FAILED" >>"$tmpdir"/FAIL
		task_change_state_to_failing "[$arch]"
	} &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
	exit 1
fi

gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:

exit 0
