#!/bin/sh -efu

. gb-sh-functions

dep="$1"; shift
dir="$1"; shift
cd "$dir"

. gb-sh-tmpdir

# We can assume that task/depends exists, unless the task is being removed.
[ -f task/depends ]

{
	# Obtain an exclusive lock on task/depends file.
	flock 0

	# sed -i is not available because of locking and permissions.
	sed "/^$dep\$/d" < "task/depends" > "$tmpdir/depends"
	cmp -s "task/depends" "$tmpdir/depends" ||
		cat < "$tmpdir/depends" > "task/depends"
} < task/depends

if [ ! -s "task/depends" ] &&
   [ POSTPONED = "$(cat task/state 2>/dev/null)" ]; then
	# Wait for a second before giving up on gb-task-queue-rebuild
	# to allow short-lived locks to expire.
	# It's safe to invoke gb-task-queue-rebuild if
	# a task lock is obtained and the task is still POSTPONED.
	flock -w 1 0 &&
	[ POSTPONED = "$(cat task/state 2>/dev/null)" ] &&
	gb-task-queue-rebuild ||:
fi <.
