#!/bin/sh -efu

. gb-sh-functions

task_id="$1"; shift
k="$((task_id/1024))"
task_dir="$GB_TASKS_DIR/$task_id"
[ -d "$task_dir" ] ||
	exit

# the repo corresponding to this task is already archived and moved to .archived/.

cd "$task_dir"

# obtain an exclusive lock on this task instance
exec <.
flock -n 0

# not archived yet?
archived_task_dir="$GB_TASKS_DIR/archive/done/_$k/$task_id"
cmp -s -- task/state "$archived_task_dir/task/state" ||
	exit

# sanity check
[ DONE = "$(cat task/state)" ]

cd "$GB_TASKS_DIR"

# redirect the entry in the task index to archive
ln -rsnf -- "$archived_task_dir" "index/$GB_REPO_NAME/done/"

# move the active instance of the archived task to .archived/.
mkdir -p -m755 .archived
mv -- "$task_id" .archived
logger -t "${0##*/}" "archived: task=$task_id"
