#!/bin/sh -efu

export LC_ALL=C

. gb-sh-functions
. gb-sh-tmpdir

arch="$1"; shift
dir="$1"; shift

[ -s plan/arepo-table-"$arch" ] || exit 0

comp=${GB_AREPO_COMPONENT_NAME:-classic}

xz -d < "$dir/$arch"/base/pkglist.$comp.xz |
	pkglist-query '%{name}-%{version}-%{release}.%{arch}.rpm\n' /dev/stdin |
		sort >"$tmpdir"/base-arepo-pkgs
cut -f3 plan/arepo-table-x86_64-i586 | sort > "$tmpdir"/arepo-pkgs

cmp "$tmpdir"/arepo-pkgs "$tmpdir"/base-arepo-pkgs >/dev/null 2>&1 || {
	stamp_echo >&2 "Patching of apt indices is broken.  Sorry for the inconvenience."
	exit 1
}

exit 0
