#!/bin/sh -eu

. gb-sh-functions

cd "$GB_TASKS_DIR/index/$GB_REPO_NAME"
states='eperm tested'
find -L $states -mindepth 1 -maxdepth 1 -type d -name '[1-9]*' -printf '%f\n' |
	sort -u |while read id; do {
		base="$GB_TASKS_DIR/$id"/build/repo/noarch/base.next
		[ -f "$base"/release -o -f "$base"/unchanged ] &&
			$0-task "$id" ||:
	} < /dev/null; done
