#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

for arch in $GB_ARCH; do
	$0-arch "$arch" "$@" || {
		me=${0##*/}
		prefix="[$arch] ${me#gb-task-}"
		stamp_echo "$prefix FAILED" >>"$tmpdir"/FAIL
		if [ -f task/fail-early -a ! -f task/abort ]; then
			touch task/abort
			stamp_echo >&2 "$prefix task abort requested"
		fi
	} &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	exit 1
fi

exit 0
