#!/bin/sh -efu

. gb-sh-functions

fail_if_task_abort_requested

. gb-sh-tmpdir

id="$(cat task/id)"
task_started "$id"

for arch in $GB_AREPO_ARCH; do
	task_started "$id" "$arch"
	if $0-arch "$arch" "$@"; then
		task_processed "$id" "$arch"
	else
		me=${0##*/}
		stamp_echo "[$arch] ${me#gb-task-arepo-} FAILED" >>"$tmpdir"/FAIL
		task_failed "$id" "$arch"
	fi &
done

wait

# Fail if at least one arch failed.
if [ -s "$tmpdir"/FAIL ]; then
	cat >&2 "$tmpdir"/FAIL
	task_failed "$id"
	exit 1
fi

task_processed "$id"

exit 0
