#!/bin/sh -efu

. gb-sh-functions

arch="$1"; shift
dir="$1"; shift

bloat=
if [ "${1-}" = '--bloat' ]; then
	bloat=$1
	shift
fi

. gb-sh-rpmhdrcache
. gb-sh-tmpdir

if [ -n "$bloat" ]; then
	# temporary repo: use 'xz --fast' mode
	set -- --bloat
	export XZ_OPT='--fast'
else
	# final repo: need more optimization
	set -- --changelog-since=2010-01-01
	export XZ_OPT='--lzma2=nice=128,depth=80,lc=4'
fi

mkdir -p "$HOME"/.cache/gen{pkg,src}list

comp=${GB_AREPO_COMPONENT_NAME:-classic}
label="${GB_REPO_LABEL:-$GB_REPO_NAME}"
description="${GB_REPO_DESCRIPTION:-ALT Linux $label}"
date_s="$(date +%s)"

genbasedir "$@" \
	--cachedir="$HOME"/.cache \
	--architecture="$arch" \
	--architectures="$arch" \
	--archive="${GB_REPO_ARCHIVE:-$description}" \
	--codename="${GB_REPO_CODENAME:-$date_s}" \
	--description="${GB_REPO_DESCRIPTION:-$description}" \
	--label="$label" \
	--origin="${GB_REPO_ORIGIN:-ALT Linux Team}" \
	--suite="${GB_REPO_SUITE:-$label}" \
	--version="${GB_REPO_VERSION:-$date_s}" \
	-s --default-key="$GB_REPO_SIGNER" \
	--topdir="$dir" \
	--flat --no-oldhashfile --mapi --bz2only --xz --no-bz2 \
	$arch $comp

[ -n "$bloat" ] || stamp_echo "[$arch] generated apt indices"
# The end of apt story.

cat > $tmpdir/ds-ignore << @@@
rpmlib(.*)
@@@

PROVIDES_FROM_DIRS=/bin:/sbin:/usr/bin:/usr/sbin

if [ -n "$bloat" -o ! -d "$dir/$arch/base/ds.$comp" ]; then
	if [ -n "$bloat" ]; then
		ds-repo -q -c gzip \
			--no-requires $tmpdir/ds-ignore \
			$dir/$arch/base/ds.$comp $dir/$arch/RPMS.$comp
	else
		ds-repo -q -c gzip \
			--references \
			--dirs "$PROVIDES_FROM_DIRS" \
			--no-requires $tmpdir/ds-ignore \
			$dir/$arch/base/ds.$comp $dir/$arch/RPMS.$comp
	fi
else
	cut -f3 plan/arepo-add-$arch | sed "s|^|$dir/$arch/RPMS.$comp/|" > $tmpdir/ds-to-add-$arch-$comp
	cp plan/arepo-rm-$arch $tmpdir/ds-to-delete-$arch-$comp

	ds-patch -q \
		$dir/$arch/base/ds.$comp \
		--add-list $tmpdir/ds-to-add-$arch-$comp \
		--del-list $tmpdir/ds-to-delete-$arch-$comp

	ds-provides -q \
		--ref-sources "$dir/$arch/base/ds.$comp" $dir/$arch/base/ds.$comp

fi

if [ -n "$bloat" ]; then
	rm -f $dir/$arch/base/ds.$comp/.rpms.complete.data
fi
