#!/bin/sh -efu

. gb-sh-functions

REPO_DIR="$1"
shift

RM()
{
	rm -v "$1"
}

CP()
{
	local deposited
	deposited=$(gb-y-deposit-file "$1")
	ln -v -- "$deposited" "$2"
	ln -v -snf -- "$deposited" "$1"
}

LN()
{
	ln -v -s "$1" "$2"
}

guess_comp()
{
	local name dir
	name="$1"; shift
	dir="$1"; shift

	comp=classic
	for c in checkinstall debuginfo; do
		if [ -z "${name##*-$c}" ]; then
			if [ -d "$dir/RPMS.$c" ]; then
				comp=$c
			fi
			break
		fi
	done
}

while read -r N EVR A F; do
	guess_comp "$N" "$REPO_DIR/$A"
	RM $REPO_DIR/$A/RPMS.$comp/$F
	RM $REPO_DIR/files/$A/RPMS/$F
done < plan/rm-bin

while read -r N EVR A F P I; do
	guess_comp "$N" "$REPO_DIR/$A"
	CP "$P" $REPO_DIR/files/$A/RPMS/$F
	LN ../../files/$A/RPMS/$F $REPO_DIR/$A/RPMS.$comp/$F
done < plan/add-bin

while read -r F A; do
	RM $REPO_DIR/$A/SRPMS.classic/$F
done < plan/rm-srpm2arch

while read -r N EVR F; do
	RM $REPO_DIR/files/SRPMS/$F
done < plan/rm-src

while read -r N EVR F P I; do
	CP "$P" $REPO_DIR/files/SRPMS/$F
done < plan/add-src

while read -r F P A; do
	LN ../../files/SRPMS/$F $REPO_DIR/$A/SRPMS.classic/$F
done < plan/add-srpm2arch
