#!/bin/sh -efu

export LC_ALL=C

. gb-sh-functions
. gb-sh-tmpdir

fail_if_task_abort_requested

REPO_DIR="$1"; shift

for arch in $GB_ARCH noarch; do
	for comp in classic debuginfo checkinstall gostcrypto; do
		list="$REPO_DIR/$arch"/base/pkglist."$comp".xz
		[ -f "$list" ] || continue
		xz -d < "$list" |
			pkglist-query '%{name}\t%{EVR}\t%{arch}\t%{name}-%{version}-%{release}.%{arch}.rpm\t%{sourcerpm}\n' /dev/stdin
	done
done > "$tmpdir"/base-bin.list

sort -u -o "$tmpdir"/base-bin.list{,}
cmp plan/next.bin "$tmpdir"/base-bin.list >/dev/null 2>&1 || {
	stamp_echo >&2 "Patching of apt indices is broken.  Sorry for the inconvenience."
	exit 1
}

exit 0
