#!/bin/sh -efu

. gb-sh-functions

arch="$1"; shift
dir="$1"; shift

bloat=
if [ "${1-}" = '--bloat' ]; then
	bloat=$1
	shift
fi

if [ -n "$bloat" ]; then
	# temporary repo: use 'xz --fast' mode
	set -- --bloat
	export XZ_OPT='--fast'
else
	# final repo: need more optimization
	set -- --changelog-since=2010-01-01
	export XZ_OPT='--lzma2=nice=128,depth=80,lc=4'
fi

mkdir -p "$HOME"/.cache/gen{pkg,src}list

comp=${GB_AREPO_COMPONENT_NAME:-classic}
label="${GB_REPO_LABEL:-$GB_REPO_NAME}"
description="${GB_REPO_DESCRIPTION:-ALT Linux $label}"
date_s="$(date +%s)"

genbasedir "$@" \
	--cachedir="$HOME"/.cache \
	--architecture="$arch" \
	--architectures="$arch" \
	--archive="${GB_REPO_ARCHIVE:-$description}" \
	--codename="${GB_REPO_CODENAME:-$date_s}" \
	--description="${GB_REPO_DESCRIPTION:-$description}" \
	--label="$label" \
	--origin="${GB_REPO_ORIGIN:-ALT Linux Team}" \
	--suite="${GB_REPO_SUITE:-$label}" \
	--version="${GB_REPO_VERSION:-$date_s}" \
	-s --default-key="$GB_INDEX_SIGNER" \
	--topdir="$dir" \
	--flat --no-oldhashfile --mapi --compressedonly --xz --no-bz2 \
	$arch $comp

[ -n "$bloat" ] || stamp_echo "[$arch] generated apt indices"
# The end of apt story.
