#!/bin/sh -efu

. shell-error

usage()
{
	[ -z "$*" ] || message "$*"
	echo >&2 "usage: $PROG <sha256sum> <timestamp>"
	exit 1
}

is_hash()
{
	[ ${#1} -eq 64 ] || return 1

	# "${1##*[![:xdigit:]]*}" does not work in ash
	[ -n "${1##*[!0123456789abcdefABCDEF]*}" ] || return 1

	return 0
}

[ $# -ge 2 ] || usage 'Not enough arguments.'
[ $# -le 2 ] || usage 'Too many arguments.'

hash="$1"; shift
is_hash "$hash" || usage 'Invalid argument.'

stamp="$1"; shift
[ "$stamp" -gt 0 ] 2>/dev/null || usage 'Invalid argument.'

dir="${hash:0:2}/${hash:2:2}"
name="${hash:4}"
filename="$dir/$name"

cd depot

finish()
{
	readlink -ev -- "$filename"
	exit 0
}

if [ -f "$filename" ]; then
	finish
fi

cleanup_tmpfile()
{
	[ -z "$tmpfile" ] || rm -f -- "$tmpfile"
	exit "$@"
}

mkdir -p -m700 .tmp
tmpfile="$(mktemp --tmpdir=.tmp -- "$hash.XXXXXX")"
trap 'cleanup_tmpfile $?' EXIT
trap 'exit 143' HUP INT QUIT PIPE TERM

cat > "$tmpfile"
echo "$hash  $tmpfile" | sha256sum --quiet -c -

header="$(od -A n -N 4 -t x1 -- "$tmpfile")"
[ "$header" = ' ed ab ee db' ] ||
	usage 'Invalid file.'

chmod 644 -- "$tmpfile"
TZ=UTC touch -d "1970-01-01 $stamp seconds" -- "$tmpfile"

umask 022
mkdir -p "$dir"

enable -f /usr/lib/bash/lockf lockf
builtin lockf -v "$dir"

if [ -f "$filename" ]; then
	finish
fi

mv -- "$tmpfile" "$filename"
tmpfile=
finish
