#!/bin/sh -efu

[ -n "$*" ] || exit 0

enable -f /usr/lib/bash/lockf lockf
builtin lockf -v "$GIT_DIR"

case "$(git config girar.repack |tr '[:upper:]' '[:lower:]')" in
	false|no|off) ;;
	*)
	echo -n 'Repacking repository... '
	git prune
	git repack -a -d
	echo done
	;;
esac

if [ -d "$GIT_DIR/refs/heads" ]; then
	echo -n 'Updating committer date cache... '
	f="$GIT_DIR/recent_committer"
	git for-each-ref "--format=%(committer)" --sort=-committerdate --count=1 refs/heads \
		>"$f"
	s="$(sed -n 's/.* \([1-9][0-9]\{9,\}\) [+-][0-9]\+$/\1/p' "$f")"
	if [ -n "$s" ]; then
		TZ=UTC touch --date="1970-01-01 $s seconds" -- "$f"
	else
		rm -f -- "$f"
	fi
	echo done
fi
