#!/bin/sh -efu

[ -n "$*" ] || exit 0

enable -f /usr/lib/bash/lockf lockf
builtin lockf -v "$GIT_DIR"

git prune
git repack -a -d
if [ -d "$GIT_DIR/refs/heads" ]; then
	git for-each-ref "--format=%(committer)" --sort=-committerdate --count=1 refs/heads \
		>"$GIT_DIR/recent_committer"
	s="$(sed -n 's/.* \([1-9][0-9]\{9,\}\) [+-][0-9]\+$/\1/p' "$GIT_DIR/recent_committer")"
	[ -z "$s" ] ||
		TZ=UTC touch --date="1970-01-01 $s seconds" -- "$GIT_DIR/recent_committer"
fi
