#!/bin/sh -eu

. girar-hooks-sh-functions

PROG=girar-update

arg_refname="${1-}"
arg_oldrev="${2-}"
arg_newrev="${3-}"

if [ -z "$arg_refname" -o -z "$arg_oldrev" -o -z "$arg_newrev" ]; then
	echo >&2 "Usage: $PROG <ref> <oldrev> <newrev>"
	exit 1
fi

init_refs

run_parts update
