#!/bin/sh -e

export IFS=' 	
'
export PATH=/sbin:/usr/sbin:/bin:/usr/bin
umask 022

. girar-admin-sh-functions

sudo_init

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME> <IDENTITY FILE>"
	exit 1
}

set_name "$1"
shift

load_identity "$1"
shift

AUTH="/etc/openssh/authorized_keys/$IT_NAME"
[ -e "$AUTH" ] ||
	fatal "error changing $NAME: authorized keys file '$AUTH' doesn't exist"

echo "restrict $IDENTITY" >> "$AUTH" ||
	fatal "error creating authorized keys file '$AUTH' for user $IT_NAME"
