#!/bin/sh -e

. girar-admin-sh-functions

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME>"
	exit 1
}

set_name "$1"
shift

gpasswd -d "$IT_NAME" "$MAINTAINERS_GROUP" ||
	fatal "error removing girar user $IT_NAME from maintainers group"
