#!/bin/sh -e

export IFS=' 	
'
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

. girar-admin-sh-functions
. shell-quote

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME>"
	exit 1
}

set_name "$1"
shift

AUTH="/etc/openssh/authorized_keys/$IT_NAME"

userdel -- "$IT_NAME" ||
	fatal "$IT_NAME: failed to remove user"

rm -f -- "$AUTH" ||
	message "$IT_NAME: failed to remove authorized keys file '$AUTH'"

quote_sed_regexp_variable Q_IT_NAME "$IT_NAME"
quote_sed_regexp_variable Q_NAME "$NAME"
quote_sed_regexp_variable Q_EMAIL_DOMAIN "$EMAIL_DOMAIN"

subst "/^$Q_IT_NAME:[[:space:]]\+$Q_NAME@$Q_EMAIL_DOMAIN.*\$/d" "$EMAIL_ALIASES" &&
	newaliases ||
	message "$IT_NAME: failed to remove email alias"
