#!/bin/sh -e

export IFS=' 	
'
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

. girar-admin-sh-functions

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME>"
	exit 1
}

set_name "$1"
shift

gpasswd -a "$IT_NAME" "$MAINTAINERS_GROUP" ||
	fatal "error adding girar user $IT_NAME to maintainers group"
