#!/bin/sh -e

. girar-admin-sh-functions

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME> < IDENTITY"
	exit 1
}

set_name "$1"
shift

load_identity

AUTH="/etc/openssh/authorized_keys/$IT_NAME"
[ -w "$AUTH" ] ||
	fatal "error changing $NAME: authorized keys file '$AUTH' doesn't exist"

echo "restrict $IDENTITY" >> "$AUTH" ||
	fatal "error creating authorized keys file '$AUTH' for user $IT_NAME"
