#!/bin/sh -e

export IFS=' 	
'
export PATH=/sbin:/usr/sbin:/bin:/usr/bin
umask 022

. girar-admin-sh-functions

sudo_init

usage()
{
	echo "$PROG: $*" >&2
	echo "usage: $PROG <NAME> <IDENTITY FILE> <GECOS>"
	exit 1
}

set_name "$1"
shift

load_identity "$1"
shift

GECOS="$*"
[ -n "$GECOS" ] ||
	usage 'not specified: GECOS'
[ -n "${GECOS//*:*/}" ] ||
	fatal "$NAME: invalid GECOS specified"

IT_SHELL="$CMD_DIR/girar-sh"

AUTH="/etc/openssh/authorized_keys/$IT_NAME"
[ ! -e "$AUTH" ] ||
	fatal "error adding $NAME: authorized keys file '$AUTH' already exists"

useradd -c "$GECOS" -d /var/empty -g "$USERS_GROUP" -G 'girar',"$TASKS_GROUP" -M -s "$IT_SHELL" "$IT_NAME" ||
	fatal "$IT_NAME: error adding user"

printf '%s:\t%s@%s\n' "$IT_NAME" "$NAME" "$EMAIL_DOMAIN" >>"$EMAIL_ALIASES" &&
	newaliases ||
	fatal "$IT_NAME: error adding email alias"

echo "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty $IDENTITY" >"$AUTH" ||
	fatal "error creating authorized keys file '$AUTH' for user $IT_NAME"

INCOMING_MOUNT="$(df -P "$INCOMING_DIR" |awk '{dir=$6} END{print dir}')"
setquota "$IT_NAME" 1048576 1310720 1024 1280 "$INCOMING_MOUNT" ||
	message "$IT_NAME: failed to set disk quota on $INCOMING_MOUNT"

for d in "$INCOMING_DIR/$NAME"; do
	install -d -o "$IT_NAME" -g girar-admin -m750 "$d" ||
		fatal "$IT_NAME: failed to create $d"
done

for f in "$TASKS_DIR/.done/$NAME"; do
	install -d -o "git_$d" -g pender -m 1770 "$d" ||
		fatal "$IT_NAME: failed to create $d"
done
