#!/bin/sh -efu

whatis="$1"; shift
owner="$1"; shift
GB_REPO_NAME="$1"; shift
GB_REPO_REAL_NAME="$1"; shift
dir="$1"; shift
arch="$1"; shift
comps="$1"; shift
noarch_comps="$1"; shift
GB_APT_CACHE_LIMIT="$1"; shift

# a simple sanity check
[ "$GB_APT_CACHE_LIMIT" -gt 1048576 ]

owner=$(printf %s "$owner" |tr . _)
repo_name=$(printf %s "$GB_REPO_NAME" |tr . _)

known_mountpoints=/proc,/dev/pts,/dev/shm
if [ -c /dev/kvm ]; then
	known_mountpoints="$known_mountpoints,/dev/kvm"
fi

# turn $dir into an absolute path
[ -n "$dir" ]
[ -z "${dir##/*}" ] ||
	dir="$HOME/$dir"

cd

# create cache directory
cache_dir="cache/$repo_name/$arch/$whatis"
mkdir -p -- "$cache_dir"
# remove stale aptbox cache if any
rm -f "$cache_dir"/chroot/aptbox.tar

# recreate directories
recreate_dirs='in apt build install base_repo hasher_repo lists'
rm -rf -- $recreate_dirs
mkdir -- $recreate_dirs

# store pkglists outside of aptbox
mkdir lists/partial

# support for full private repo
rm -rf gb-repo
ln -s base_repo gb-repo

# recreate ~/hasher symlink
rm -rf hasher
ln -s -- "$TMPDIR/hasher"

# recreate hasher config file
mkdir -p .hasher
cat >.hasher/config <<EOF
workdir="\$TMPDIR/hasher"
mkdir -p -- "\$workdir"

apt_config="\$HOME/apt/apt.conf"
def_target="$arch"
def_repo="\$HOME/hasher_repo"
cache_dir="\$HOME/$cache_dir"
known_mountpoints="$known_mountpoints"
USER="$owner-$repo_name"
EOF

# pass remaining command line arguments (if any) to .hasher/config
for arg; do
	printf '%s\n' "$arg"
done >>.hasher/config

# recreate hasher install hook
mkdir -p .hasher/install
case "$whatis" in
	install)
		rm -f .hasher/install/post
		;;
	*)
		cat >.hasher/install/post <<'EOF'
#!/bin/sh -efu
exec find /usr/share/locale/ -mindepth 3 -maxdepth 3 -type f -name '*.mo' -delete
EOF
		chmod a+x .hasher/install/post
		;;
esac

# recreate apt config files
cat >apt/apt.conf <<EOF
Dir::Etc::main "/dev/null";
Dir::Etc::parts "/var/empty";
Dir::Etc::sourceparts "/var/empty";
Dir::Etc::sourcelist "$HOME/apt/sources.list";
Dir::Etc::pkgpriorities "$HOME/apt/pkgpriorities";
Dir::State::lists "$HOME/lists";
Debug::pkgMarkInstall "true";
Debug::pkgProblemResolver "true";
APT::Cache-Limit "$GB_APT_CACHE_LIMIT";
EOF
cat >apt/sources.list <<EOF
rpm file:$dir $arch $comps
rpm file:$dir noarch $noarch_comps
EOF
cat >apt/pkgpriorities <<EOF
Important:
  basesystem
Required:
  apt
Standard:
  etcnet
  kernel-doc
  libfftw3-devel
  libpam0
  libpam0-devel
  maxima-bin-gcl
  postfix
  python-dev
  python-modules-tkinter
  clang10.0
  clang10.0-analyzer
  clang10.0-devel
  clang10.0-devel-static
  clang10.0-doc
  clang10.0-libs
  lld10.0
  lld10.0-devel
  lld10.0-doc
  llvm10.0
  llvm10.0-devel
  llvm10.0-devel-static
  llvm10.0-doc
  llvm10.0-libs
  clang11.0
  clang11.0-analyzer
  clang11.0-devel
  clang11.0-devel-static
  clang11.0-doc
  clang11.0-libs
  lld11.0
  lld11.0-devel
  lld11.0-doc
  llvm11.0
  llvm11.0-devel
  llvm11.0-devel-static
  llvm11.0-doc
  llvm11.0-libs
  altlinux-release-$GB_REPO_REAL_NAME
  branding-alt-$GB_REPO_REAL_NAME-alterator
  branding-alt-$GB_REPO_REAL_NAME-bootloader
  branding-alt-$GB_REPO_REAL_NAME-bootsplash
  branding-alt-$GB_REPO_REAL_NAME-gnome-settings
  branding-alt-$GB_REPO_REAL_NAME-graphics
  branding-alt-$GB_REPO_REAL_NAME-indexhtml
  branding-alt-$GB_REPO_REAL_NAME-kde3-settings
  branding-alt-$GB_REPO_REAL_NAME-kde4-settings
  branding-alt-$GB_REPO_REAL_NAME-notes
  branding-alt-$GB_REPO_REAL_NAME-slideshow
  branding-alt-$GB_REPO_REAL_NAME-themes
  branding-alt-$GB_REPO_REAL_NAME-xfce-settings
  branding-altlinux-$GB_REPO_REAL_NAME-alterator
  branding-altlinux-$GB_REPO_REAL_NAME-bootloader
  branding-altlinux-$GB_REPO_REAL_NAME-bootsplash
  branding-altlinux-$GB_REPO_REAL_NAME-gnome-settings
  branding-altlinux-$GB_REPO_REAL_NAME-graphics
  branding-altlinux-$GB_REPO_REAL_NAME-indexhtml
  branding-altlinux-$GB_REPO_REAL_NAME-kde3-settings
  branding-altlinux-$GB_REPO_REAL_NAME-kde4-settings
  branding-altlinux-$GB_REPO_REAL_NAME-notes
  branding-altlinux-$GB_REPO_REAL_NAME-slideshow
  branding-altlinux-$GB_REPO_REAL_NAME-themes
  branding-altlinux-$GB_REPO_REAL_NAME-xfce-settings
EOF

# recreate ~/.rpmmacros
cat >.rpmmacros <<EOF
%_topdir	$HOME/RPM
%_tmppath	$TMPDIR
%_priority_distbranch	$GB_REPO_NAME
%_rpmscript_werror	1
EOF
