#!/bin/sh -efu

arch="$1"; shift
from="$1"; shift
tag_name="$1"; shift
package_signer="$1"; shift
dist="$1"; shift
task_id="$1"; shift
subtask_id="$1"; shift
try="$1"; shift
iter="$1"; shift
swift=
if [ "${1-}" = swift ]; then
	swift="$1"; shift
fi

if [ -z "${from##*.src.rpm}" ]; then
	src="$from"
	build_env_flags=--install-only
else
	src=pkg.tar
	build_env_flags=--build-srpm-only
fi
build_source=in/"$src"

oneliner()
{
	printf %s "$*" |tr -s '[:space:]' ' '
}

stamp_echo()
{
	echo "$(LC_TIME=C date -u '+%Y-%b-%d %T') :: $(oneliner "$*")"
}

arch_prefix="[$arch] "
I="$arch_prefix$from${tag_name:+ $tag_name}: remote"

Fatal()
{
	stamp_echo >&2 "$I: $*"
	exit 1
}

tmpdir=
cleanup()
{
	[ -z "$tmpdir" ] || rm -rf -- "$tmpdir"
	[ ! -d in ] || find in -mindepth 1 -delete
	exit "$@"
}
trap 'cleanup $?' EXIT
trap 'exit 143' HUP INT QUIT PIPE TERM

if [ -n "$swift" -a -s build/chroot_base -a -f build/chroot_BR ]; then
	mkdir -p hasher_repo/$arch/RPMS.hasher hasher_repo/SRPMS.hasher
	(set +f
	 cp -p build/rpms/*.rpm hasher_repo/$arch/RPMS.hasher/ &&
	 cp -p build/srpm/*.rpm hasher_repo/SRPMS.hasher/ ) ||
		Fatal 'failed to obtain packages from previous run'
	echo swept > build/status
	exit 0
fi

tmpdir=$(mktemp -dt "${0##*/}.XXXXXXXX")

# Step 1: initialize and query hasher chroot.
setarch "$arch" -- \
hsh --init --no-repackage-source ${package_signer:+--packager="$package_signer"} >"$tmpdir"/out 2>&1 || {
	sed "s/^/$arch_prefix/" "$tmpdir"/out
	Fatal 'initroot failed'
} >&2

q_bin='%{name}\t%|serial?{%{serial}:}|%{version}-%{release}\t%{arch}\t%{sourcerpm}\t%{sha1header}\n'
hsh-run -- rpmquery -a --qf "$q_bin" >"$tmpdir"/chroot_base
sort -u -o "$tmpdir"/chroot_base{,}

# Step 1a: check if rebuild is needed at all.
# When earlier src.rpm is available, it is *almost* okay to reuse its BuildRequires
# to calculate the list of packages that *would* have been installed into chroot.
if cmp -s {build,"$tmpdir"}/chroot_base; then
	build_deps=$(set +f; rpmquery -pR build/srpm/*.rpm)
	build_deps=$(printf %s "$build_deps" |grep -v '^rpmlib(' |tr -d [[:blank:]])
	(set +u
	    . hsh-sh-functions
	    set_workdir
	    print_uris $build_deps 2>/dev/null ) |
	xargs -r0 --delimiter='\n' \
		rpmquery --qf "$q_bin" -p -- |
		sort -u >"$tmpdir"/chroot_BR
	if cmp -s {build,"$tmpdir"}/chroot_BR; then
		(set +f
		 cp -p build/rpms/*.rpm hasher_repo/$arch/RPMS.hasher/ &&
		 cp -p build/srpm/*.rpm hasher_repo/SRPMS.hasher/ ) ||
			Fatal 'failed to obtain packages from previous run'
		echo cached > build/status
		exit 0
	fi
fi

# initialize %package_signer before parsing spec.
cat <<EOF |hsh-run -- sh -c 'cat >> ~/.rpmmacros'
%package_signer	${package_signer:-%packager}
%distribution	ALT ${dist/sisyphus/Sisyphus}
%disttag	$dist+$task_id.$subtask_id.$try.$iter
# neutralize ubt
%ubt	%nil
EOF

# generate $RPM_STRICT_INTERDEPS
cat <<EOF |hsh-run -- sh -c 'cat >> ~/.profile'
export RPM_STRICT_INTERDEPS="$dist.$task_id.$subtask_id.$try.$iter"
EOF

# Step 2: examine repo/SRPMS.hasher contents before srpm build.
find hasher_repo/SRPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm' \
	-printf '%f\t%D %i %s %T@\n' >"$tmpdir"/srpm0
sort -o "$tmpdir"/srpm0{,}

# Step 3: install build environment, build src.rpm (if needed), without sisyphus_check.
rm -f build/excluded
hsh-rebuild $build_env_flags --repo-src="$tmpdir"/srpm --query-repackage --no-sisyphus-check "$build_source" \
	>build/srpm.log 2>&1 ||
	{
		if egrep -qs '^error: Architecture is (excluded|not included): ' build/srpm.log; then
			egrep '^error: Architecture is (excluded|not included): ' \
				build/srpm.log >build/excluded
			echo excluded > build/status
			exit 0
		fi
		sed "s/^/$arch_prefix/" build/srpm.log
		[ "$arch" = armh ] ||
			Fatal 'cannot build src.rpm'
		echo 'Cannot build src.rpm' > build/excluded
		echo excluded > build/status
		stamp_echo >&2 "$I: cannot build src.rpm, but we don't care"
		exit 0
	} >&2

# Step 4: examine BuildRequires.
hsh-run -- rpmquery -a --qf "$q_bin" >"$tmpdir"/chroot_BR
sort -u -o "$tmpdir"/chroot_base{,}
sort -u -o "$tmpdir"/chroot_BR{,}
comm -23 "$tmpdir"/chroot_BR "$tmpdir"/chroot_base >"$tmpdir"/chroot_BR+
mv -f "$tmpdir"/chroot_BR+ "$tmpdir"/chroot_BR

# Step 5: check if rebuild is needed at all.
if cmp -s {build,"$tmpdir"}/chroot_base; then
	if cmp -s {build,"$tmpdir"}/chroot_BR; then
		(set +f
		 cp -p build/rpms/*.rpm hasher_repo/$arch/RPMS.hasher/ &&
		 cp -p build/srpm/*.rpm hasher_repo/SRPMS.hasher/ ) ||
			Fatal 'failed to obtain packages from previous run'
		echo cached > build/status
		exit 0
	fi
fi
if [ "$src" = pkg.tar ]; then
	find "$tmpdir"/srpm/ -mindepth 1 -maxdepth 1 -type f -name '*.src.rpm' \
		-exec mv -t hasher_repo/SRPMS.hasher/ -- '{}' '+'
else
	mv "$build_source" hasher_repo/SRPMS.hasher/
fi

# Step 6: examine repo/SRPMS.hasher contents after srpm build.
find hasher_repo/SRPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm' \
	-printf '%f\t%D %i %s %T@\n' >"$tmpdir"/srpm1
sort -o "$tmpdir"/srpm1{,}

comm -23 "$tmpdir"/srpm{0,1} >"$tmpdir"/out
[ ! -s "$tmpdir"/out ] ||
	Fatal 'attempt to replace source packages: ' "$(cut -f1 <"$tmpdir"/out)"

comm -23 "$tmpdir"/srpm{1,0} |cut -f1 >"$tmpdir"/add-src
[ -s "$tmpdir"/add-src ] ||
	Fatal 'no source package'

n=$(wc -l <"$tmpdir"/add-src)
[ "$n" -eq 1 ] ||
	Fatal 'multiple source packages: ' "$(cat "$tmpdir"/add-src)"

read sname <"$tmpdir"/add-src
build_source=hasher_repo/SRPMS.hasher/"$sname"

# Step 7: examine repo/<arch> contents before build.
find hasher_repo/$arch/RPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm' \
	-printf '%f\t%D %i %s %T@\n' >"$tmpdir"/rpms1
sort -o "$tmpdir"/rpms1{,}

# Step 8: build.
rm -f "$tmpdir"/OK{1,2}
{
	hsh-rebuild --query-repackage "$build_source" 2>&1 &&
		touch "$tmpdir"/OK1 ||:
} | {
	gawk 'BEGIN{ts0=systime()}{print strftime("[%T]",systime()-ts0,1),$0}' > build/log &&
		touch "$tmpdir"/OK2 ||:
}
[ -f "$tmpdir"/OK1 -a -f "$tmpdir"/OK2 ] || {
	. ./gb-remote-log
	sed -r 's/^\[[0-9]{2}(:[0-9]{2}){2}\] //' build/log |
		buildlog_errors |
		sed "s/^/$arch_prefix/"
	Fatal 'build failed'
} >&2
hsh-rmchroot

# Step 9: examine repo/ contents after build.
find hasher_repo/SRPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm' \
	-printf '%f\t%D %i %s %T@\n' >"$tmpdir"/srpm2
sort -o "$tmpdir"/srpm2{,}

if ! cmp "$tmpdir"/srpm{1,2} >/dev/null; then
	Fatal 'unexpected change of source packages'
fi >&2

find hasher_repo/$arch/RPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm' \
	-printf '%f\t%D %i %s %T@\n' >"$tmpdir"/rpms2
sort -o "$tmpdir"/rpms2{,}

comm -23 "$tmpdir"/rpms{1,2} >"$tmpdir"/out
[ ! -s "$tmpdir"/out ] ||
	Fatal 'attempt to replace binary packages: ' "$(cut -f1 <"$tmpdir"/out)"

# Step 10: save results.
comm -23 "$tmpdir"/rpms{2,1} |cut -f1 >"$tmpdir"/add-bin
[ -s "$tmpdir"/add-bin ] ||
	Fatal 'no binary packages'

# Check that we've got (src,bin+) tuple.
(cd hasher_repo/$arch/RPMS.hasher
 xargs -r <"$tmpdir"/add-bin \
	rpmquery --qf '%{SOURCERPM}\n' -p ) >"$tmpdir"/ref-src || false
sort -u -o "$tmpdir"/ref-src{,}
(cd "$tmpdir" && diff -U1 {add,ref}-src ) ||
	Fatal 'binary packages refer wrong %{SOURCERPM}'

# Copyout.
> "$tmpdir"/FAIL

rm -rf build/rpms
mkdir -p build/rpms
{
	tar -C hasher_repo/$arch/RPMS.hasher -cf - `cat "$tmpdir"/add-bin` ||
		echo "FAILED: tar -C hasher_repo/$arch/RPMS.hasher -cf" >> "$tmpdir"/FAIL
} |
{
	tar -C build/rpms -xf - ||
		echo "FAILED: tar -C build/rpms -xf" >> "$tmpdir"/FAIL
}

if [ -s "$tmpdir"/FAIL ]; then
	sed >&2 "s/^/$arch_prefix/" "$tmpdir"/FAIL
	exit 1
fi

rm -rf build/srpm
mkdir -p build/srpm
{
	tar -C hasher_repo/SRPMS.hasher -cf - `cat "$tmpdir"/add-src` ||
		echo "FAILED: tar -C hasher_repo/SRPMS.hasher -cf" >> "$tmpdir"/FAIL
} |
{
	tar -C build/srpm -xf - ||
		echo "FAILED: tar -C build/srpm -xf" >> "$tmpdir"/FAIL
}

if [ -s "$tmpdir"/FAIL ]; then
	sed >&2 "s/^/$arch_prefix/" "$tmpdir"/FAIL
	exit 1
fi

# Meta copyout.
cp -p "$tmpdir"/chroot_base build/chroot_base
cp -p "$tmpdir"/chroot_BR build/chroot_BR

echo built > build/status
