#!/bin/sh -efu

whatis="$1"; shift
owner="$1"; shift
GB_REPO_NAME="$1"; shift
dir="$1"; shift
arch="$1"; shift
comps="$1"; shift
GB_APT_CACHE_LIMIT="$1"; shift

# a simple sanity check
[ "$GB_APT_CACHE_LIMIT" -gt 1048576 ]

owner=$(printf %s "$owner" |tr . _)
repo_name=$(printf %s "$GB_REPO_NAME" |tr . _)

# turn $dir into an absolute path
[ -n "$dir" ]
[ -z "${dir##/*}" ] ||
	dir="$HOME/$dir"

cd

# create cache directory
cache_dir="cache/$repo_name/$arch/$whatis"
mkdir -p -- "$cache_dir"

# recreate directories
recreate_dirs='in apt build install base_repo hasher_repo lists'
rm -rf -- $recreate_dirs
mkdir -- $recreate_dirs

# store pkglists outside of aptbox
mkdir lists/partial

# support for full private repo
rm -f gb-repo
ln -s base_repo gb-repo

# recreate ~/hasher symlink
rm -rf hasher
ln -s -- "$TMPDIR/hasher"

# recreate hasher config file
mkdir -p -- .hasher
cat >.hasher/config <<EOF
workdir="\$TMPDIR/hasher"
mkdir -p -- "\$workdir"

apt_config="\$HOME/apt/apt.conf"
def_target="$arch"
def_repo="\$HOME/hasher_repo"
cache_dir="\$HOME/$cache_dir"
nprocs=1
known_mountpoints=/proc,/dev/pts
USER="$owner-$repo_name"
EOF

# pass remaining command line arguments (if any) to .hasher/config
for arg; do
	printf '%s\n' "$arg"
done >>.hasher/config

# recreate apt config files
cat >apt/apt.conf <<EOF
Dir::Etc::main "/dev/null";
Dir::Etc::parts "/var/empty";
Dir::Etc::sourceparts "/var/empty";
Dir::Etc::sourcelist "$HOME/apt/sources.list";
Dir::Etc::pkgpriorities "$HOME/apt/pkgpriorities";
Dir::State::lists "$HOME/lists";
Debug::pkgMarkInstall "true";
Debug::pkgProblemResolver "true";
APT::Cache-Limit "$GB_APT_CACHE_LIMIT";
EOF
cat >apt/sources.list <<EOF
rpm file:$dir $arch $comps
rpm file:$dir noarch classic
EOF
cat >apt/pkgpriorities <<EOF
Important:
  basesystem
Required:
  apt
Standard:
  kernel-doc
  libpam0
  libpam0-devel
  maxima-bin-gcl
  postfix
  python-dev
  python-modules-tkinter
  altlinux-release-$GB_REPO_NAME
  branding-altlinux-office-server-alterator
  branding-altlinux-office-server-bootloader
  branding-altlinux-office-server-bootsplash
  branding-altlinux-office-server-graphics
  branding-altlinux-office-server-indexhtml
  branding-altlinux-office-server-notes
  branding-altlinux-office-server-slideshow
EOF

# recreate ~/.rpmmacros
cat >.rpmmacros <<EOF
%_topdir	$HOME/RPM
%_tmppath	$TMPDIR
EOF
