#!/bin/sh -efu

. ga-sh-functions

[ -n "${GA_SQUEEZE_MTIME-}" ] &&
[ "${GA_SQUEEZE_MTIME-}" -gt 0 ] || exit 0

repo="$1"; shift

task_list="$GA_REPO_ROOT/$repo/task/task.list"
squeeze_list="$GA_REPO_ROOT/$repo/task/squeeze.list"
upload_list="$GA_UPLOAD_DIR/log/snapshot/$repo.log"
[ -f "$task_list" ] || exit 0
[ -f "$squeeze_list" ] || exit 0
[ -f "$upload_list" ] || exit 0

. girar-sh-tmpdir
cd "$tmpdir"

tail -n +2 "$task_list" > task.list
sort -u -o task.list{,}

sort -u "$squeeze_list" "$upload_list" > skip.list

comm -23 task.list skip.list > todo.list
sort -n -o todo.list{,}

xargs -rn1 "$0-task" "$repo" < todo.list
