#!/bin/sh -efu

rpmargs="$1"; shift
dir="$1"; shift
arch="$1"; shift

cd

# recreate $TMPDIR/tmp
# recreate ~/tmp as symlink to $TMPDIR/tmp
tmpdir="$TMPDIR/tmp"
rm -rf -- "$tmpdir"
mkdir -p -- "$tmpdir"
rm -rf tmp
ln -snf -- "$tmpdir"

# recreate $TMPDIR/build
# recreate ~/build as symlink to $TMPDIR/build
build="$TMPDIR/build"
rm -rf -- "$build"
mkdir -p -- "$build"
ln -snf -- "$build"

# create $TMPDIR/hasher if necessary
# recreate $TMPDIR/hasher/repo
# recreate ~/hasher as symlink to $TMPDIR/hasher
workdir="$TMPDIR/hasher"
mkdir -p -- "$workdir"
ln -snf -- "$workdir"
rm -rf -- "$workdir/repo"

# support for full private repo
gb_repo="$TMPDIR/gb-repo"
rm -rf -- "$gb_repo"
mkdir -p -- "$gb_repo"
ln -snf -- "$gb_repo"

# recreate hasher config file
mkdir -p -- .hasher
cat >.hasher/config <<EOF
workdir="\$TMPDIR/hasher"
apt_config="\$workdir/apt.conf"
def_target="$arch"
nprocs=1
known_mountpoints=/proc
rpmargs="$rpmargs"
EOF

# recreate apt config files
cat >"$workdir/apt.conf" <<EOF
Dir::Etc::main "/dev/null";
Dir::Etc::parts "/var/empty";
Dir::Etc::sourceparts "/var/empty";
Dir::Etc::sourcelist "$workdir/sources.list";
EOF
cat >"$workdir/sources.list" <<EOF
rpm file:$dir $arch classic
rpm file:$dir noarch classic
EOF
